/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  Address,
  Contract,
  ContractState,
  TestContractResult,
  HexString,
  ContractFactory,
  EventSubscribeOptions,
  EventSubscription,
  CallContractParams,
  CallContractResult,
  TestContractParams,
  ContractEvent,
  subscribeContractEvent,
  subscribeContractEvents,
  testMethod,
  callMethod,
  multicallMethods,
  fetchContractState,
  Asset,
  ContractInstance,
  getContractEventsCurrentCount,
  TestContractParamsWithoutMaps,
  TestContractResultWithoutMaps,
  SignExecuteContractMethodParams,
  SignExecuteScriptTxResult,
  signExecuteMethod,
  addStdIdToFields,
  encodeContractFields,
  Narrow,
} from "@alephium/web3";
import { default as Bridge0ContractJson } from "../Bridge0.ral.json";
import { getContractByCodeHash, registerContract } from "./contracts";
import * as types from "./types";

// Custom types for the contract
export namespace Bridge0Types {
  export type Fields = {
    dex: HexString;
    master: Address;
    accountTemplate: HexString;
    sequencer: [
      Address,
      Address,
      Address,
      Address,
      Address,
      Address,
      Address,
      Address,
      Address,
      Address,
      Address,
      Address,
      Address,
      Address,
      Address,
      Address,
      Address,
      Address,
      Address,
      Address,
      Address,
      Address,
      Address,
      Address,
      Address,
      Address,
      Address,
      Address,
      Address,
      Address,
      Address,
      Address
    ];
    t: bigint;
  };

  export type State = ContractState<Fields>;

  export interface CallMethodTable {
    statelessVerify: {
      params: CallContractParams<{
        k: HexString;
        data: HexString;
        sig: HexString;
        caller: Address;
      }>;
      result: CallContractResult<boolean>;
    };
    timeInRange: {
      params: CallContractParams<{ time: bigint }>;
      result: CallContractResult<boolean>;
    };
    verify: {
      params: CallContractParams<{ s: bigint; time: bigint }>;
      result: CallContractResult<boolean>;
    };
    updateTime: {
      params: Omit<CallContractParams<{}>, "args">;
      result: CallContractResult<null>;
    };
    transfer: {
      params: CallContractParams<{
        s: bigint;
        time: bigint;
        id: HexString;
        p: types.Transfer;
        sig: HexString;
        sig2: HexString;
      }>;
      result: CallContractResult<null>;
    };
    exchange: {
      params: CallContractParams<{
        s: bigint;
        time: bigint;
        id: HexString;
        p: types.Exchange;
        sig: HexString;
        sig2: HexString;
      }>;
      result: CallContractResult<null>;
    };
    rekey: {
      params: CallContractParams<{
        s: bigint;
        time: bigint;
        id: HexString;
        p: types.Rekey;
        sig: HexString;
      }>;
      result: CallContractResult<null>;
    };
    createPair: {
      params: CallContractParams<{
        s: bigint;
        time: bigint;
        id: HexString;
        p: types.CreatePool;
        sig: HexString;
      }>;
      result: CallContractResult<null>;
    };
    modifyPosition: {
      params: CallContractParams<{
        s: bigint;
        time: bigint;
        id: HexString;
        p: types.ModifyPosition;
        sig: HexString;
      }>;
      result: CallContractResult<null>;
    };
    swap: {
      params: CallContractParams<{
        s: bigint;
        time: bigint;
        id: HexString;
        p: types.Swap;
        sig: HexString;
        priceLimit: bigint;
      }>;
      result: CallContractResult<null>;
    };
    donate: {
      params: CallContractParams<{
        s: bigint;
        time: bigint;
        id: HexString;
        p: types.Donate;
        sig: HexString;
      }>;
      result: CallContractResult<null>;
    };
    closePosition: {
      params: CallContractParams<{
        s: bigint;
        time: bigint;
        id: HexString;
        p: types.ModifyPosition;
      }>;
      result: CallContractResult<null>;
    };
    exitPosition: {
      params: CallContractParams<{
        key: HexString;
        p: types.ModifyPosition;
        sig: HexString;
      }>;
      result: CallContractResult<null>;
    };
    setSequencer: {
      params: CallContractParams<{ s: bigint; newSequencer: Address }>;
      result: CallContractResult<null>;
    };
    deposit: {
      params: CallContractParams<{
        id: HexString;
        key: HexString;
        p: types.Deposit;
        sig: HexString;
        tokens: HexString;
      }>;
      result: CallContractResult<HexString>;
    };
    forceClose: {
      params: CallContractParams<{
        key: HexString;
        p: types.ForceClose;
        sig: HexString;
      }>;
      result: CallContractResult<null>;
    };
    asyncTransfer: {
      params: CallContractParams<{
        key: HexString;
        p: types.AsyncTransfer;
        sig: HexString;
      }>;
      result: CallContractResult<null>;
    };
    forceTransfer: {
      params: CallContractParams<{
        s: bigint;
        time: bigint;
        key: HexString;
        tokenId: HexString;
      }>;
      result: CallContractResult<null>;
    };
    addPermissionedAccount: {
      params: CallContractParams<{ p: types.Deposit; sig: HexString }>;
      result: CallContractResult<null>;
    };
    clawback: {
      params: CallContractParams<{
        s: bigint;
        time: bigint;
        id: HexString;
        p: types.Clawback;
        sig: HexString;
      }>;
      result: CallContractResult<null>;
    };
  }
  export type CallMethodParams<T extends keyof CallMethodTable> =
    CallMethodTable[T]["params"];
  export type CallMethodResult<T extends keyof CallMethodTable> =
    CallMethodTable[T]["result"];
  export type MultiCallParams = Partial<{
    [Name in keyof CallMethodTable]: CallMethodTable[Name]["params"];
  }>;
  export type MultiCallResults<T extends MultiCallParams> = {
    [MaybeName in keyof T]: MaybeName extends keyof CallMethodTable
      ? CallMethodTable[MaybeName]["result"]
      : undefined;
  };
  export type MulticallReturnType<Callss extends MultiCallParams[]> = {
    [index in keyof Callss]: MultiCallResults<Callss[index]>;
  };

  export interface SignExecuteMethodTable {
    statelessVerify: {
      params: SignExecuteContractMethodParams<{
        k: HexString;
        data: HexString;
        sig: HexString;
        caller: Address;
      }>;
      result: SignExecuteScriptTxResult;
    };
    timeInRange: {
      params: SignExecuteContractMethodParams<{ time: bigint }>;
      result: SignExecuteScriptTxResult;
    };
    verify: {
      params: SignExecuteContractMethodParams<{ s: bigint; time: bigint }>;
      result: SignExecuteScriptTxResult;
    };
    updateTime: {
      params: Omit<SignExecuteContractMethodParams<{}>, "args">;
      result: SignExecuteScriptTxResult;
    };
    transfer: {
      params: SignExecuteContractMethodParams<{
        s: bigint;
        time: bigint;
        id: HexString;
        p: types.Transfer;
        sig: HexString;
        sig2: HexString;
      }>;
      result: SignExecuteScriptTxResult;
    };
    exchange: {
      params: SignExecuteContractMethodParams<{
        s: bigint;
        time: bigint;
        id: HexString;
        p: types.Exchange;
        sig: HexString;
        sig2: HexString;
      }>;
      result: SignExecuteScriptTxResult;
    };
    rekey: {
      params: SignExecuteContractMethodParams<{
        s: bigint;
        time: bigint;
        id: HexString;
        p: types.Rekey;
        sig: HexString;
      }>;
      result: SignExecuteScriptTxResult;
    };
    createPair: {
      params: SignExecuteContractMethodParams<{
        s: bigint;
        time: bigint;
        id: HexString;
        p: types.CreatePool;
        sig: HexString;
      }>;
      result: SignExecuteScriptTxResult;
    };
    modifyPosition: {
      params: SignExecuteContractMethodParams<{
        s: bigint;
        time: bigint;
        id: HexString;
        p: types.ModifyPosition;
        sig: HexString;
      }>;
      result: SignExecuteScriptTxResult;
    };
    swap: {
      params: SignExecuteContractMethodParams<{
        s: bigint;
        time: bigint;
        id: HexString;
        p: types.Swap;
        sig: HexString;
        priceLimit: bigint;
      }>;
      result: SignExecuteScriptTxResult;
    };
    donate: {
      params: SignExecuteContractMethodParams<{
        s: bigint;
        time: bigint;
        id: HexString;
        p: types.Donate;
        sig: HexString;
      }>;
      result: SignExecuteScriptTxResult;
    };
    closePosition: {
      params: SignExecuteContractMethodParams<{
        s: bigint;
        time: bigint;
        id: HexString;
        p: types.ModifyPosition;
      }>;
      result: SignExecuteScriptTxResult;
    };
    exitPosition: {
      params: SignExecuteContractMethodParams<{
        key: HexString;
        p: types.ModifyPosition;
        sig: HexString;
      }>;
      result: SignExecuteScriptTxResult;
    };
    setSequencer: {
      params: SignExecuteContractMethodParams<{
        s: bigint;
        newSequencer: Address;
      }>;
      result: SignExecuteScriptTxResult;
    };
    deposit: {
      params: SignExecuteContractMethodParams<{
        id: HexString;
        key: HexString;
        p: types.Deposit;
        sig: HexString;
        tokens: HexString;
      }>;
      result: SignExecuteScriptTxResult;
    };
    forceClose: {
      params: SignExecuteContractMethodParams<{
        key: HexString;
        p: types.ForceClose;
        sig: HexString;
      }>;
      result: SignExecuteScriptTxResult;
    };
    asyncTransfer: {
      params: SignExecuteContractMethodParams<{
        key: HexString;
        p: types.AsyncTransfer;
        sig: HexString;
      }>;
      result: SignExecuteScriptTxResult;
    };
    forceTransfer: {
      params: SignExecuteContractMethodParams<{
        s: bigint;
        time: bigint;
        key: HexString;
        tokenId: HexString;
      }>;
      result: SignExecuteScriptTxResult;
    };
    addPermissionedAccount: {
      params: SignExecuteContractMethodParams<{
        p: types.Deposit;
        sig: HexString;
      }>;
      result: SignExecuteScriptTxResult;
    };
    clawback: {
      params: SignExecuteContractMethodParams<{
        s: bigint;
        time: bigint;
        id: HexString;
        p: types.Clawback;
        sig: HexString;
      }>;
      result: SignExecuteScriptTxResult;
    };
  }
  export type SignExecuteMethodParams<T extends keyof SignExecuteMethodTable> =
    SignExecuteMethodTable[T]["params"];
  export type SignExecuteMethodResult<T extends keyof SignExecuteMethodTable> =
    SignExecuteMethodTable[T]["result"];
}

class Factory extends ContractFactory<Bridge0Instance, Bridge0Types.Fields> {
  encodeFields(fields: Bridge0Types.Fields) {
    return encodeContractFields(
      addStdIdToFields(this.contract, fields),
      this.contract.fieldsSig,
      types.AllStructs
    );
  }

  consts = {
    Msg: {
      Rekey: BigInt("0"),
      Transfer: BigInt("1"),
      Receive: BigInt("2"),
      ModifyPosition: BigInt("3"),
      CreatePool: BigInt("4"),
      Clawback: BigInt("5"),
      Exchange: BigInt("6"),
      Exchange2: BigInt("7"),
      ExitPosition: BigInt("8"),
      Deposit: BigInt("9"),
      ForceClose: BigInt("10"),
      AsyncTransfer: BigInt("11"),
      Swap: BigInt("12"),
      Donate: BigInt("13"),
    },
  };

  at(address: string): Bridge0Instance {
    return new Bridge0Instance(address);
  }

  tests = {
    statelessVerify: async (
      params: TestContractParamsWithoutMaps<
        Bridge0Types.Fields,
        { k: HexString; data: HexString; sig: HexString; caller: Address }
      >
    ): Promise<TestContractResultWithoutMaps<boolean>> => {
      return testMethod(this, "statelessVerify", params, getContractByCodeHash);
    },
    timeInRange: async (
      params: TestContractParamsWithoutMaps<
        Bridge0Types.Fields,
        { time: bigint }
      >
    ): Promise<TestContractResultWithoutMaps<boolean>> => {
      return testMethod(this, "timeInRange", params, getContractByCodeHash);
    },
    verify: async (
      params: TestContractParamsWithoutMaps<
        Bridge0Types.Fields,
        { s: bigint; time: bigint }
      >
    ): Promise<TestContractResultWithoutMaps<boolean>> => {
      return testMethod(this, "verify", params, getContractByCodeHash);
    },
    updateTime: async (
      params: Omit<
        TestContractParamsWithoutMaps<Bridge0Types.Fields, never>,
        "args"
      >
    ): Promise<TestContractResultWithoutMaps<null>> => {
      return testMethod(this, "updateTime", params, getContractByCodeHash);
    },
    transfer: async (
      params: TestContractParamsWithoutMaps<
        Bridge0Types.Fields,
        {
          s: bigint;
          time: bigint;
          id: HexString;
          p: types.Transfer;
          sig: HexString;
          sig2: HexString;
        }
      >
    ): Promise<TestContractResultWithoutMaps<null>> => {
      return testMethod(this, "transfer", params, getContractByCodeHash);
    },
    exchange: async (
      params: TestContractParamsWithoutMaps<
        Bridge0Types.Fields,
        {
          s: bigint;
          time: bigint;
          id: HexString;
          p: types.Exchange;
          sig: HexString;
          sig2: HexString;
        }
      >
    ): Promise<TestContractResultWithoutMaps<null>> => {
      return testMethod(this, "exchange", params, getContractByCodeHash);
    },
    rekey: async (
      params: TestContractParamsWithoutMaps<
        Bridge0Types.Fields,
        {
          s: bigint;
          time: bigint;
          id: HexString;
          p: types.Rekey;
          sig: HexString;
        }
      >
    ): Promise<TestContractResultWithoutMaps<null>> => {
      return testMethod(this, "rekey", params, getContractByCodeHash);
    },
    createPair: async (
      params: TestContractParamsWithoutMaps<
        Bridge0Types.Fields,
        {
          s: bigint;
          time: bigint;
          id: HexString;
          p: types.CreatePool;
          sig: HexString;
        }
      >
    ): Promise<TestContractResultWithoutMaps<null>> => {
      return testMethod(this, "createPair", params, getContractByCodeHash);
    },
    modifyPosition: async (
      params: TestContractParamsWithoutMaps<
        Bridge0Types.Fields,
        {
          s: bigint;
          time: bigint;
          id: HexString;
          p: types.ModifyPosition;
          sig: HexString;
        }
      >
    ): Promise<TestContractResultWithoutMaps<null>> => {
      return testMethod(this, "modifyPosition", params, getContractByCodeHash);
    },
    swap: async (
      params: TestContractParamsWithoutMaps<
        Bridge0Types.Fields,
        {
          s: bigint;
          time: bigint;
          id: HexString;
          p: types.Swap;
          sig: HexString;
          priceLimit: bigint;
        }
      >
    ): Promise<TestContractResultWithoutMaps<null>> => {
      return testMethod(this, "swap", params, getContractByCodeHash);
    },
    donate: async (
      params: TestContractParamsWithoutMaps<
        Bridge0Types.Fields,
        {
          s: bigint;
          time: bigint;
          id: HexString;
          p: types.Donate;
          sig: HexString;
        }
      >
    ): Promise<TestContractResultWithoutMaps<null>> => {
      return testMethod(this, "donate", params, getContractByCodeHash);
    },
    closePosition: async (
      params: TestContractParamsWithoutMaps<
        Bridge0Types.Fields,
        { s: bigint; time: bigint; id: HexString; p: types.ModifyPosition }
      >
    ): Promise<TestContractResultWithoutMaps<null>> => {
      return testMethod(this, "closePosition", params, getContractByCodeHash);
    },
    exitPosition: async (
      params: TestContractParamsWithoutMaps<
        Bridge0Types.Fields,
        { key: HexString; p: types.ModifyPosition; sig: HexString }
      >
    ): Promise<TestContractResultWithoutMaps<null>> => {
      return testMethod(this, "exitPosition", params, getContractByCodeHash);
    },
    setSequencer: async (
      params: TestContractParamsWithoutMaps<
        Bridge0Types.Fields,
        { s: bigint; newSequencer: Address }
      >
    ): Promise<TestContractResultWithoutMaps<null>> => {
      return testMethod(this, "setSequencer", params, getContractByCodeHash);
    },
    deposit: async (
      params: TestContractParamsWithoutMaps<
        Bridge0Types.Fields,
        {
          id: HexString;
          key: HexString;
          p: types.Deposit;
          sig: HexString;
          tokens: HexString;
        }
      >
    ): Promise<TestContractResultWithoutMaps<HexString>> => {
      return testMethod(this, "deposit", params, getContractByCodeHash);
    },
    forceClose: async (
      params: TestContractParamsWithoutMaps<
        Bridge0Types.Fields,
        { key: HexString; p: types.ForceClose; sig: HexString }
      >
    ): Promise<TestContractResultWithoutMaps<null>> => {
      return testMethod(this, "forceClose", params, getContractByCodeHash);
    },
    asyncTransfer: async (
      params: TestContractParamsWithoutMaps<
        Bridge0Types.Fields,
        { key: HexString; p: types.AsyncTransfer; sig: HexString }
      >
    ): Promise<TestContractResultWithoutMaps<null>> => {
      return testMethod(this, "asyncTransfer", params, getContractByCodeHash);
    },
    forceTransfer: async (
      params: TestContractParamsWithoutMaps<
        Bridge0Types.Fields,
        { s: bigint; time: bigint; key: HexString; tokenId: HexString }
      >
    ): Promise<TestContractResultWithoutMaps<null>> => {
      return testMethod(this, "forceTransfer", params, getContractByCodeHash);
    },
    addPermissionedAccount: async (
      params: TestContractParamsWithoutMaps<
        Bridge0Types.Fields,
        { p: types.Deposit; sig: HexString }
      >
    ): Promise<TestContractResultWithoutMaps<null>> => {
      return testMethod(
        this,
        "addPermissionedAccount",
        params,
        getContractByCodeHash
      );
    },
    clawback: async (
      params: TestContractParamsWithoutMaps<
        Bridge0Types.Fields,
        {
          s: bigint;
          time: bigint;
          id: HexString;
          p: types.Clawback;
          sig: HexString;
        }
      >
    ): Promise<TestContractResultWithoutMaps<null>> => {
      return testMethod(this, "clawback", params, getContractByCodeHash);
    },
  };

  stateForTest(
    initFields: Bridge0Types.Fields,
    asset?: Asset,
    address?: string
  ) {
    return this.stateForTest_(initFields, asset, address, undefined);
  }
}

// Use this object to test and deploy the contract
export const Bridge0 = new Factory(
  Contract.fromJson(
    Bridge0ContractJson,
    "",
    "b7d1728a221826bd2cfd1f50f95b97cdfa2de491f5dc6120ac858987980c2696",
    types.AllStructs
  )
);
registerContract(Bridge0);

// Use this class to interact with the blockchain
export class Bridge0Instance extends ContractInstance {
  constructor(address: Address) {
    super(address);
  }

  async fetchState(): Promise<Bridge0Types.State> {
    return fetchContractState(Bridge0, this);
  }

  view = {
    statelessVerify: async (
      params: Bridge0Types.CallMethodParams<"statelessVerify">
    ): Promise<Bridge0Types.CallMethodResult<"statelessVerify">> => {
      return callMethod(
        Bridge0,
        this,
        "statelessVerify",
        params,
        getContractByCodeHash
      );
    },
    timeInRange: async (
      params: Bridge0Types.CallMethodParams<"timeInRange">
    ): Promise<Bridge0Types.CallMethodResult<"timeInRange">> => {
      return callMethod(
        Bridge0,
        this,
        "timeInRange",
        params,
        getContractByCodeHash
      );
    },
    verify: async (
      params: Bridge0Types.CallMethodParams<"verify">
    ): Promise<Bridge0Types.CallMethodResult<"verify">> => {
      return callMethod(Bridge0, this, "verify", params, getContractByCodeHash);
    },
    updateTime: async (
      params?: Bridge0Types.CallMethodParams<"updateTime">
    ): Promise<Bridge0Types.CallMethodResult<"updateTime">> => {
      return callMethod(
        Bridge0,
        this,
        "updateTime",
        params === undefined ? {} : params,
        getContractByCodeHash
      );
    },
    transfer: async (
      params: Bridge0Types.CallMethodParams<"transfer">
    ): Promise<Bridge0Types.CallMethodResult<"transfer">> => {
      return callMethod(
        Bridge0,
        this,
        "transfer",
        params,
        getContractByCodeHash
      );
    },
    exchange: async (
      params: Bridge0Types.CallMethodParams<"exchange">
    ): Promise<Bridge0Types.CallMethodResult<"exchange">> => {
      return callMethod(
        Bridge0,
        this,
        "exchange",
        params,
        getContractByCodeHash
      );
    },
    rekey: async (
      params: Bridge0Types.CallMethodParams<"rekey">
    ): Promise<Bridge0Types.CallMethodResult<"rekey">> => {
      return callMethod(Bridge0, this, "rekey", params, getContractByCodeHash);
    },
    createPair: async (
      params: Bridge0Types.CallMethodParams<"createPair">
    ): Promise<Bridge0Types.CallMethodResult<"createPair">> => {
      return callMethod(
        Bridge0,
        this,
        "createPair",
        params,
        getContractByCodeHash
      );
    },
    modifyPosition: async (
      params: Bridge0Types.CallMethodParams<"modifyPosition">
    ): Promise<Bridge0Types.CallMethodResult<"modifyPosition">> => {
      return callMethod(
        Bridge0,
        this,
        "modifyPosition",
        params,
        getContractByCodeHash
      );
    },
    swap: async (
      params: Bridge0Types.CallMethodParams<"swap">
    ): Promise<Bridge0Types.CallMethodResult<"swap">> => {
      return callMethod(Bridge0, this, "swap", params, getContractByCodeHash);
    },
    donate: async (
      params: Bridge0Types.CallMethodParams<"donate">
    ): Promise<Bridge0Types.CallMethodResult<"donate">> => {
      return callMethod(Bridge0, this, "donate", params, getContractByCodeHash);
    },
    closePosition: async (
      params: Bridge0Types.CallMethodParams<"closePosition">
    ): Promise<Bridge0Types.CallMethodResult<"closePosition">> => {
      return callMethod(
        Bridge0,
        this,
        "closePosition",
        params,
        getContractByCodeHash
      );
    },
    exitPosition: async (
      params: Bridge0Types.CallMethodParams<"exitPosition">
    ): Promise<Bridge0Types.CallMethodResult<"exitPosition">> => {
      return callMethod(
        Bridge0,
        this,
        "exitPosition",
        params,
        getContractByCodeHash
      );
    },
    setSequencer: async (
      params: Bridge0Types.CallMethodParams<"setSequencer">
    ): Promise<Bridge0Types.CallMethodResult<"setSequencer">> => {
      return callMethod(
        Bridge0,
        this,
        "setSequencer",
        params,
        getContractByCodeHash
      );
    },
    deposit: async (
      params: Bridge0Types.CallMethodParams<"deposit">
    ): Promise<Bridge0Types.CallMethodResult<"deposit">> => {
      return callMethod(
        Bridge0,
        this,
        "deposit",
        params,
        getContractByCodeHash
      );
    },
    forceClose: async (
      params: Bridge0Types.CallMethodParams<"forceClose">
    ): Promise<Bridge0Types.CallMethodResult<"forceClose">> => {
      return callMethod(
        Bridge0,
        this,
        "forceClose",
        params,
        getContractByCodeHash
      );
    },
    asyncTransfer: async (
      params: Bridge0Types.CallMethodParams<"asyncTransfer">
    ): Promise<Bridge0Types.CallMethodResult<"asyncTransfer">> => {
      return callMethod(
        Bridge0,
        this,
        "asyncTransfer",
        params,
        getContractByCodeHash
      );
    },
    forceTransfer: async (
      params: Bridge0Types.CallMethodParams<"forceTransfer">
    ): Promise<Bridge0Types.CallMethodResult<"forceTransfer">> => {
      return callMethod(
        Bridge0,
        this,
        "forceTransfer",
        params,
        getContractByCodeHash
      );
    },
    addPermissionedAccount: async (
      params: Bridge0Types.CallMethodParams<"addPermissionedAccount">
    ): Promise<Bridge0Types.CallMethodResult<"addPermissionedAccount">> => {
      return callMethod(
        Bridge0,
        this,
        "addPermissionedAccount",
        params,
        getContractByCodeHash
      );
    },
    clawback: async (
      params: Bridge0Types.CallMethodParams<"clawback">
    ): Promise<Bridge0Types.CallMethodResult<"clawback">> => {
      return callMethod(
        Bridge0,
        this,
        "clawback",
        params,
        getContractByCodeHash
      );
    },
  };

  transact = {
    statelessVerify: async (
      params: Bridge0Types.SignExecuteMethodParams<"statelessVerify">
    ): Promise<Bridge0Types.SignExecuteMethodResult<"statelessVerify">> => {
      return signExecuteMethod(Bridge0, this, "statelessVerify", params);
    },
    timeInRange: async (
      params: Bridge0Types.SignExecuteMethodParams<"timeInRange">
    ): Promise<Bridge0Types.SignExecuteMethodResult<"timeInRange">> => {
      return signExecuteMethod(Bridge0, this, "timeInRange", params);
    },
    verify: async (
      params: Bridge0Types.SignExecuteMethodParams<"verify">
    ): Promise<Bridge0Types.SignExecuteMethodResult<"verify">> => {
      return signExecuteMethod(Bridge0, this, "verify", params);
    },
    updateTime: async (
      params: Bridge0Types.SignExecuteMethodParams<"updateTime">
    ): Promise<Bridge0Types.SignExecuteMethodResult<"updateTime">> => {
      return signExecuteMethod(Bridge0, this, "updateTime", params);
    },
    transfer: async (
      params: Bridge0Types.SignExecuteMethodParams<"transfer">
    ): Promise<Bridge0Types.SignExecuteMethodResult<"transfer">> => {
      return signExecuteMethod(Bridge0, this, "transfer", params);
    },
    exchange: async (
      params: Bridge0Types.SignExecuteMethodParams<"exchange">
    ): Promise<Bridge0Types.SignExecuteMethodResult<"exchange">> => {
      return signExecuteMethod(Bridge0, this, "exchange", params);
    },
    rekey: async (
      params: Bridge0Types.SignExecuteMethodParams<"rekey">
    ): Promise<Bridge0Types.SignExecuteMethodResult<"rekey">> => {
      return signExecuteMethod(Bridge0, this, "rekey", params);
    },
    createPair: async (
      params: Bridge0Types.SignExecuteMethodParams<"createPair">
    ): Promise<Bridge0Types.SignExecuteMethodResult<"createPair">> => {
      return signExecuteMethod(Bridge0, this, "createPair", params);
    },
    modifyPosition: async (
      params: Bridge0Types.SignExecuteMethodParams<"modifyPosition">
    ): Promise<Bridge0Types.SignExecuteMethodResult<"modifyPosition">> => {
      return signExecuteMethod(Bridge0, this, "modifyPosition", params);
    },
    swap: async (
      params: Bridge0Types.SignExecuteMethodParams<"swap">
    ): Promise<Bridge0Types.SignExecuteMethodResult<"swap">> => {
      return signExecuteMethod(Bridge0, this, "swap", params);
    },
    donate: async (
      params: Bridge0Types.SignExecuteMethodParams<"donate">
    ): Promise<Bridge0Types.SignExecuteMethodResult<"donate">> => {
      return signExecuteMethod(Bridge0, this, "donate", params);
    },
    closePosition: async (
      params: Bridge0Types.SignExecuteMethodParams<"closePosition">
    ): Promise<Bridge0Types.SignExecuteMethodResult<"closePosition">> => {
      return signExecuteMethod(Bridge0, this, "closePosition", params);
    },
    exitPosition: async (
      params: Bridge0Types.SignExecuteMethodParams<"exitPosition">
    ): Promise<Bridge0Types.SignExecuteMethodResult<"exitPosition">> => {
      return signExecuteMethod(Bridge0, this, "exitPosition", params);
    },
    setSequencer: async (
      params: Bridge0Types.SignExecuteMethodParams<"setSequencer">
    ): Promise<Bridge0Types.SignExecuteMethodResult<"setSequencer">> => {
      return signExecuteMethod(Bridge0, this, "setSequencer", params);
    },
    deposit: async (
      params: Bridge0Types.SignExecuteMethodParams<"deposit">
    ): Promise<Bridge0Types.SignExecuteMethodResult<"deposit">> => {
      return signExecuteMethod(Bridge0, this, "deposit", params);
    },
    forceClose: async (
      params: Bridge0Types.SignExecuteMethodParams<"forceClose">
    ): Promise<Bridge0Types.SignExecuteMethodResult<"forceClose">> => {
      return signExecuteMethod(Bridge0, this, "forceClose", params);
    },
    asyncTransfer: async (
      params: Bridge0Types.SignExecuteMethodParams<"asyncTransfer">
    ): Promise<Bridge0Types.SignExecuteMethodResult<"asyncTransfer">> => {
      return signExecuteMethod(Bridge0, this, "asyncTransfer", params);
    },
    forceTransfer: async (
      params: Bridge0Types.SignExecuteMethodParams<"forceTransfer">
    ): Promise<Bridge0Types.SignExecuteMethodResult<"forceTransfer">> => {
      return signExecuteMethod(Bridge0, this, "forceTransfer", params);
    },
    addPermissionedAccount: async (
      params: Bridge0Types.SignExecuteMethodParams<"addPermissionedAccount">
    ): Promise<
      Bridge0Types.SignExecuteMethodResult<"addPermissionedAccount">
    > => {
      return signExecuteMethod(Bridge0, this, "addPermissionedAccount", params);
    },
    clawback: async (
      params: Bridge0Types.SignExecuteMethodParams<"clawback">
    ): Promise<Bridge0Types.SignExecuteMethodResult<"clawback">> => {
      return signExecuteMethod(Bridge0, this, "clawback", params);
    },
  };

  async multicall<Calls extends Bridge0Types.MultiCallParams>(
    calls: Calls
  ): Promise<Bridge0Types.MultiCallResults<Calls>>;
  async multicall<Callss extends Bridge0Types.MultiCallParams[]>(
    callss: Narrow<Callss>
  ): Promise<Bridge0Types.MulticallReturnType<Callss>>;
  async multicall<
    Callss extends Bridge0Types.MultiCallParams | Bridge0Types.MultiCallParams[]
  >(callss: Callss): Promise<unknown> {
    return await multicallMethods(Bridge0, this, callss, getContractByCodeHash);
  }
}
