/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  Address,
  Contract,
  ContractState,
  TestContractResult,
  HexString,
  ContractFactory,
  EventSubscribeOptions,
  EventSubscription,
  CallContractParams,
  CallContractResult,
  TestContractParams,
  ContractEvent,
  subscribeContractEvent,
  subscribeContractEvents,
  testMethod,
  callMethod,
  multicallMethods,
  fetchContractState,
  Asset,
  ContractInstance,
  getContractEventsCurrentCount,
  TestContractParamsWithoutMaps,
  TestContractResultWithoutMaps,
  SignExecuteContractMethodParams,
  SignExecuteScriptTxResult,
  signExecuteMethod,
  addStdIdToFields,
  encodeContractFields,
  Narrow,
} from "@alephium/web3";
import { default as CounterMut2ContractJson } from "../CounterMut2.ral.json";
import { getContractByCodeHash, registerContract } from "./contracts";
import * as types from "./types";

// Custom types for the contract
export namespace CounterMut2Types {
  export type Fields = {
    value: [
      bigint,
      bigint,
      bigint,
      bigint,
      bigint,
      bigint,
      bigint,
      bigint,
      bigint,
      bigint,
      bigint,
      bigint,
      bigint,
      bigint,
      bigint,
      bigint,
      bigint,
      bigint,
      bigint,
      bigint,
      bigint,
      bigint,
      bigint,
      bigint,
      bigint,
      bigint,
      bigint,
      bigint,
      bigint,
      bigint,
      bigint,
      bigint,
      bigint,
      bigint,
      bigint,
      bigint,
      bigint,
      bigint,
      bigint,
      bigint,
      bigint,
      bigint,
      bigint,
      bigint,
      bigint,
      bigint,
      bigint,
      bigint,
      bigint,
      bigint,
      bigint,
      bigint,
      bigint,
      bigint,
      bigint,
      bigint,
      bigint,
      bigint,
      bigint,
      bigint,
      bigint,
      bigint,
      bigint,
      bigint,
      bigint,
      bigint,
      bigint,
      bigint,
      bigint,
      bigint,
      bigint,
      bigint,
      bigint,
      bigint,
      bigint,
      bigint,
      bigint,
      bigint,
      bigint,
      bigint,
      bigint,
      bigint,
      bigint,
      bigint,
      bigint,
      bigint,
      bigint,
      bigint,
      bigint,
      bigint,
      bigint,
      bigint
    ];
  };

  export type State = ContractState<Fields>;

  export interface CallMethodTable {
    inc: {
      params: CallContractParams<{ at: bigint }>;
      result: CallContractResult<null>;
    };
    get: {
      params: CallContractParams<{ at: bigint }>;
      result: CallContractResult<bigint>;
    };
  }
  export type CallMethodParams<T extends keyof CallMethodTable> =
    CallMethodTable[T]["params"];
  export type CallMethodResult<T extends keyof CallMethodTable> =
    CallMethodTable[T]["result"];
  export type MultiCallParams = Partial<{
    [Name in keyof CallMethodTable]: CallMethodTable[Name]["params"];
  }>;
  export type MultiCallResults<T extends MultiCallParams> = {
    [MaybeName in keyof T]: MaybeName extends keyof CallMethodTable
      ? CallMethodTable[MaybeName]["result"]
      : undefined;
  };
  export type MulticallReturnType<Callss extends MultiCallParams[]> = {
    [index in keyof Callss]: MultiCallResults<Callss[index]>;
  };

  export interface SignExecuteMethodTable {
    inc: {
      params: SignExecuteContractMethodParams<{ at: bigint }>;
      result: SignExecuteScriptTxResult;
    };
    get: {
      params: SignExecuteContractMethodParams<{ at: bigint }>;
      result: SignExecuteScriptTxResult;
    };
  }
  export type SignExecuteMethodParams<T extends keyof SignExecuteMethodTable> =
    SignExecuteMethodTable[T]["params"];
  export type SignExecuteMethodResult<T extends keyof SignExecuteMethodTable> =
    SignExecuteMethodTable[T]["result"];
}

class Factory extends ContractFactory<
  CounterMut2Instance,
  CounterMut2Types.Fields
> {
  encodeFields(fields: CounterMut2Types.Fields) {
    return encodeContractFields(
      addStdIdToFields(this.contract, fields),
      this.contract.fieldsSig,
      types.AllStructs
    );
  }

  at(address: string): CounterMut2Instance {
    return new CounterMut2Instance(address);
  }

  tests = {
    inc: async (
      params: TestContractParamsWithoutMaps<
        CounterMut2Types.Fields,
        { at: bigint }
      >
    ): Promise<TestContractResultWithoutMaps<null>> => {
      return testMethod(this, "inc", params, getContractByCodeHash);
    },
    get: async (
      params: TestContractParamsWithoutMaps<
        CounterMut2Types.Fields,
        { at: bigint }
      >
    ): Promise<TestContractResultWithoutMaps<bigint>> => {
      return testMethod(this, "get", params, getContractByCodeHash);
    },
  };

  stateForTest(
    initFields: CounterMut2Types.Fields,
    asset?: Asset,
    address?: string
  ) {
    return this.stateForTest_(initFields, asset, address, undefined);
  }
}

// Use this object to test and deploy the contract
export const CounterMut2 = new Factory(
  Contract.fromJson(
    CounterMut2ContractJson,
    "",
    "2cd18d2fdc4851265b1234121e81837f9951f1a2760b9eb1be0afbdd61fa6ce2",
    types.AllStructs
  )
);
registerContract(CounterMut2);

// Use this class to interact with the blockchain
export class CounterMut2Instance extends ContractInstance {
  constructor(address: Address) {
    super(address);
  }

  async fetchState(): Promise<CounterMut2Types.State> {
    return fetchContractState(CounterMut2, this);
  }

  view = {
    inc: async (
      params: CounterMut2Types.CallMethodParams<"inc">
    ): Promise<CounterMut2Types.CallMethodResult<"inc">> => {
      return callMethod(
        CounterMut2,
        this,
        "inc",
        params,
        getContractByCodeHash
      );
    },
    get: async (
      params: CounterMut2Types.CallMethodParams<"get">
    ): Promise<CounterMut2Types.CallMethodResult<"get">> => {
      return callMethod(
        CounterMut2,
        this,
        "get",
        params,
        getContractByCodeHash
      );
    },
  };

  transact = {
    inc: async (
      params: CounterMut2Types.SignExecuteMethodParams<"inc">
    ): Promise<CounterMut2Types.SignExecuteMethodResult<"inc">> => {
      return signExecuteMethod(CounterMut2, this, "inc", params);
    },
    get: async (
      params: CounterMut2Types.SignExecuteMethodParams<"get">
    ): Promise<CounterMut2Types.SignExecuteMethodResult<"get">> => {
      return signExecuteMethod(CounterMut2, this, "get", params);
    },
  };

  async multicall<Calls extends CounterMut2Types.MultiCallParams>(
    calls: Calls
  ): Promise<CounterMut2Types.MultiCallResults<Calls>>;
  async multicall<Callss extends CounterMut2Types.MultiCallParams[]>(
    callss: Narrow<Callss>
  ): Promise<CounterMut2Types.MulticallReturnType<Callss>>;
  async multicall<
    Callss extends
      | CounterMut2Types.MultiCallParams
      | CounterMut2Types.MultiCallParams[]
  >(callss: Callss): Promise<unknown> {
    return await multicallMethods(
      CounterMut2,
      this,
      callss,
      getContractByCodeHash
    );
  }
}
