/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  RunScriptResult,
  DeployContractExecutionResult,
  NetworkId,
} from "@alephium/web3";
import {
  Pool,
  PoolInstance,
  Position,
  PositionInstance,
  Tick,
  TickInstance,
  BitmapWord,
  BitmapWordInstance,
  PoolConfig,
  PoolConfigInstance,
  DexAccount,
  DexAccountInstance,
  PoolFactory,
  PoolFactoryInstance,
  PositionManager,
  PositionManagerInstance,
} from ".";
import { default as testnetDeployments } from "../../deployments/.deployments.testnet.json";
import { default as devnetDeployments } from "../../deployments/.deployments.devnet.json";

export type Deployments = {
  deployerAddress: string;
  contracts: {
    Pool: DeployContractExecutionResult<PoolInstance>;
    Position: DeployContractExecutionResult<PositionInstance>;
    Tick: DeployContractExecutionResult<TickInstance>;
    BitmapWord: DeployContractExecutionResult<BitmapWordInstance>;
    PoolConfig: DeployContractExecutionResult<PoolConfigInstance>;
    PoolFactory: DeployContractExecutionResult<PoolFactoryInstance>;
    PositionManager: DeployContractExecutionResult<PositionManagerInstance>;
    DexAccount?: DeployContractExecutionResult<DexAccountInstance>;
  };
};

function toDeployments(json: any): Deployments {
  const contracts = {
    Pool: {
      ...json.contracts["Pool"],
      contractInstance: Pool.at(
        json.contracts["Pool"].contractInstance.address
      ),
    },
    Position: {
      ...json.contracts["Position"],
      contractInstance: Position.at(
        json.contracts["Position"].contractInstance.address
      ),
    },
    Tick: {
      ...json.contracts["Tick"],
      contractInstance: Tick.at(
        json.contracts["Tick"].contractInstance.address
      ),
    },
    BitmapWord: {
      ...json.contracts["BitmapWord"],
      contractInstance: BitmapWord.at(
        json.contracts["BitmapWord"].contractInstance.address
      ),
    },
    PoolConfig: {
      ...json.contracts["PoolConfig"],
      contractInstance: PoolConfig.at(
        json.contracts["PoolConfig"].contractInstance.address
      ),
    },
    PoolFactory: {
      ...json.contracts["PoolFactory"],
      contractInstance: PoolFactory.at(
        json.contracts["PoolFactory"].contractInstance.address
      ),
    },
    PositionManager: {
      ...json.contracts["PositionManager"],
      contractInstance: PositionManager.at(
        json.contracts["PositionManager"].contractInstance.address
      ),
    },
    DexAccount:
      json.contracts["DexAccount"] === undefined
        ? undefined
        : {
            ...json.contracts["DexAccount"],
            contractInstance: DexAccount.at(
              json.contracts["DexAccount"].contractInstance.address
            ),
          },
  };
  return {
    ...json,
    contracts: contracts as Deployments["contracts"],
  };
}

export function loadDeployments(
  networkId: NetworkId,
  deployerAddress?: string
): Deployments {
  const deployments =
    networkId === "testnet"
      ? testnetDeployments
      : networkId === "devnet"
      ? devnetDeployments
      : undefined;
  if (deployments === undefined) {
    throw Error("The contract has not been deployed to the " + networkId);
  }
  const allDeployments: any[] = Array.isArray(deployments)
    ? deployments
    : [deployments];
  if (deployerAddress === undefined) {
    if (allDeployments.length > 1) {
      throw Error(
        "The contract has been deployed multiple times on " +
          networkId +
          ", please specify the deployer address"
      );
    } else {
      return toDeployments(allDeployments[0]);
    }
  }
  const result = allDeployments.find(
    (d) => d.deployerAddress === deployerAddress
  );
  if (result === undefined) {
    throw Error("The contract deployment result does not exist");
  }
  return toDeployments(result);
}
