/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  Address,
  Contract,
  ContractState,
  TestContractResult,
  HexString,
  ContractFactory,
  EventSubscribeOptions,
  EventSubscription,
  CallContractParams,
  CallContractResult,
  TestContractParams,
  ContractEvent,
  subscribeContractEvent,
  subscribeContractEvents,
  testMethod,
  callMethod,
  multicallMethods,
  fetchContractState,
  Asset,
  ContractInstance,
  getContractEventsCurrentCount,
  TestContractParamsWithoutMaps,
  TestContractResultWithoutMaps,
  SignExecuteContractMethodParams,
  SignExecuteScriptTxResult,
  signExecuteMethod,
  addStdIdToFields,
  encodeContractFields,
  Narrow,
} from "@alephium/web3";
import { default as DexAccountRootContractJson } from "../DexAccountRoot.ral.json";
import { getContractByCodeHash, registerContract } from "./contracts";
import * as types from "./types";

// Custom types for the contract
export namespace DexAccountRootTypes {
  export type Fields = {
    templateId: HexString;
    owner: Address;
    parents: [HexString, HexString];
    minSwapCount: bigint;
  };

  export type State = ContractState<Fields>;

  export type OwnerUpdatedEvent = ContractEvent<{
    previousOwner: Address;
    newOwner: Address;
  }>;
  export type ClmmParentSetEvent = ContractEvent<{ clmmParent: HexString }>;
  export type CpmmParentSetEvent = ContractEvent<{ cpmmParent: HexString }>;
  export type MinSwapCountUpdatedEvent = ContractEvent<{
    previousMinSwapCount: bigint;
    newMinSwapCount: bigint;
  }>;

  export interface CallMethodTable {
    setCpmmParent: {
      params: CallContractParams<{ cpmmParent: HexString }>;
      result: CallContractResult<null>;
    };
    createAccount: {
      params: CallContractParams<{ ref: Address }>;
      result: CallContractResult<null>;
    };
    updateOwner: {
      params: CallContractParams<{ newOwner: Address }>;
      result: CallContractResult<null>;
    };
    setClmmParent: {
      params: CallContractParams<{ clmmParent: HexString }>;
      result: CallContractResult<null>;
    };
    updateMinSwapCount: {
      params: CallContractParams<{ newMinSwapCount: bigint }>;
      result: CallContractResult<null>;
    };
    upgrade: {
      params: CallContractParams<{
        newCode: HexString;
        immFields: HexString;
        mutFields: HexString;
      }>;
      result: CallContractResult<null>;
    };
    upgradeDexAccount: {
      params: CallContractParams<{
        newCode: HexString;
        dexAccount: HexString;
        immFields: HexString;
        mutFields: HexString;
      }>;
      result: CallContractResult<null>;
    };
  }
  export type CallMethodParams<T extends keyof CallMethodTable> =
    CallMethodTable[T]["params"];
  export type CallMethodResult<T extends keyof CallMethodTable> =
    CallMethodTable[T]["result"];
  export type MultiCallParams = Partial<{
    [Name in keyof CallMethodTable]: CallMethodTable[Name]["params"];
  }>;
  export type MultiCallResults<T extends MultiCallParams> = {
    [MaybeName in keyof T]: MaybeName extends keyof CallMethodTable
      ? CallMethodTable[MaybeName]["result"]
      : undefined;
  };
  export type MulticallReturnType<Callss extends MultiCallParams[]> = {
    [index in keyof Callss]: MultiCallResults<Callss[index]>;
  };

  export interface SignExecuteMethodTable {
    setCpmmParent: {
      params: SignExecuteContractMethodParams<{ cpmmParent: HexString }>;
      result: SignExecuteScriptTxResult;
    };
    createAccount: {
      params: SignExecuteContractMethodParams<{ ref: Address }>;
      result: SignExecuteScriptTxResult;
    };
    updateOwner: {
      params: SignExecuteContractMethodParams<{ newOwner: Address }>;
      result: SignExecuteScriptTxResult;
    };
    setClmmParent: {
      params: SignExecuteContractMethodParams<{ clmmParent: HexString }>;
      result: SignExecuteScriptTxResult;
    };
    updateMinSwapCount: {
      params: SignExecuteContractMethodParams<{ newMinSwapCount: bigint }>;
      result: SignExecuteScriptTxResult;
    };
    upgrade: {
      params: SignExecuteContractMethodParams<{
        newCode: HexString;
        immFields: HexString;
        mutFields: HexString;
      }>;
      result: SignExecuteScriptTxResult;
    };
    upgradeDexAccount: {
      params: SignExecuteContractMethodParams<{
        newCode: HexString;
        dexAccount: HexString;
        immFields: HexString;
        mutFields: HexString;
      }>;
      result: SignExecuteScriptTxResult;
    };
  }
  export type SignExecuteMethodParams<T extends keyof SignExecuteMethodTable> =
    SignExecuteMethodTable[T]["params"];
  export type SignExecuteMethodResult<T extends keyof SignExecuteMethodTable> =
    SignExecuteMethodTable[T]["result"];
}

class Factory extends ContractFactory<
  DexAccountRootInstance,
  DexAccountRootTypes.Fields
> {
  encodeFields(fields: DexAccountRootTypes.Fields) {
    return encodeContractFields(
      addStdIdToFields(this.contract, fields),
      this.contract.fieldsSig,
      types.AllStructs
    );
  }

  eventIndex = {
    OwnerUpdated: 0,
    ClmmParentSet: 1,
    CpmmParentSet: 2,
    MinSwapCountUpdated: 3,
  };

  at(address: string): DexAccountRootInstance {
    return new DexAccountRootInstance(address);
  }

  tests = {
    setCpmmParent: async (
      params: TestContractParamsWithoutMaps<
        DexAccountRootTypes.Fields,
        { cpmmParent: HexString }
      >
    ): Promise<TestContractResultWithoutMaps<null>> => {
      return testMethod(this, "setCpmmParent", params, getContractByCodeHash);
    },
    createAccount: async (
      params: TestContractParamsWithoutMaps<
        DexAccountRootTypes.Fields,
        { ref: Address }
      >
    ): Promise<TestContractResultWithoutMaps<null>> => {
      return testMethod(this, "createAccount", params, getContractByCodeHash);
    },
    updateOwner: async (
      params: TestContractParamsWithoutMaps<
        DexAccountRootTypes.Fields,
        { newOwner: Address }
      >
    ): Promise<TestContractResultWithoutMaps<null>> => {
      return testMethod(this, "updateOwner", params, getContractByCodeHash);
    },
    setClmmParent: async (
      params: TestContractParamsWithoutMaps<
        DexAccountRootTypes.Fields,
        { clmmParent: HexString }
      >
    ): Promise<TestContractResultWithoutMaps<null>> => {
      return testMethod(this, "setClmmParent", params, getContractByCodeHash);
    },
    updateMinSwapCount: async (
      params: TestContractParamsWithoutMaps<
        DexAccountRootTypes.Fields,
        { newMinSwapCount: bigint }
      >
    ): Promise<TestContractResultWithoutMaps<null>> => {
      return testMethod(
        this,
        "updateMinSwapCount",
        params,
        getContractByCodeHash
      );
    },
    upgrade: async (
      params: TestContractParamsWithoutMaps<
        DexAccountRootTypes.Fields,
        { newCode: HexString; immFields: HexString; mutFields: HexString }
      >
    ): Promise<TestContractResultWithoutMaps<null>> => {
      return testMethod(this, "upgrade", params, getContractByCodeHash);
    },
    upgradeDexAccount: async (
      params: TestContractParamsWithoutMaps<
        DexAccountRootTypes.Fields,
        {
          newCode: HexString;
          dexAccount: HexString;
          immFields: HexString;
          mutFields: HexString;
        }
      >
    ): Promise<TestContractResultWithoutMaps<null>> => {
      return testMethod(
        this,
        "upgradeDexAccount",
        params,
        getContractByCodeHash
      );
    },
  };

  stateForTest(
    initFields: DexAccountRootTypes.Fields,
    asset?: Asset,
    address?: string
  ) {
    return this.stateForTest_(initFields, asset, address, undefined);
  }
}

// Use this object to test and deploy the contract
export const DexAccountRoot = new Factory(
  Contract.fromJson(
    DexAccountRootContractJson,
    "",
    "91147a10aa362e845648421f32a2e5a680bed1128eea82c164e8075d550d7258",
    types.AllStructs
  )
);
registerContract(DexAccountRoot);

// Use this class to interact with the blockchain
export class DexAccountRootInstance extends ContractInstance {
  constructor(address: Address) {
    super(address);
  }

  async fetchState(): Promise<DexAccountRootTypes.State> {
    return fetchContractState(DexAccountRoot, this);
  }

  async getContractEventsCurrentCount(): Promise<number> {
    return getContractEventsCurrentCount(this.address);
  }

  subscribeOwnerUpdatedEvent(
    options: EventSubscribeOptions<DexAccountRootTypes.OwnerUpdatedEvent>,
    fromCount?: number
  ): EventSubscription {
    return subscribeContractEvent(
      DexAccountRoot.contract,
      this,
      options,
      "OwnerUpdated",
      fromCount
    );
  }

  subscribeClmmParentSetEvent(
    options: EventSubscribeOptions<DexAccountRootTypes.ClmmParentSetEvent>,
    fromCount?: number
  ): EventSubscription {
    return subscribeContractEvent(
      DexAccountRoot.contract,
      this,
      options,
      "ClmmParentSet",
      fromCount
    );
  }

  subscribeCpmmParentSetEvent(
    options: EventSubscribeOptions<DexAccountRootTypes.CpmmParentSetEvent>,
    fromCount?: number
  ): EventSubscription {
    return subscribeContractEvent(
      DexAccountRoot.contract,
      this,
      options,
      "CpmmParentSet",
      fromCount
    );
  }

  subscribeMinSwapCountUpdatedEvent(
    options: EventSubscribeOptions<DexAccountRootTypes.MinSwapCountUpdatedEvent>,
    fromCount?: number
  ): EventSubscription {
    return subscribeContractEvent(
      DexAccountRoot.contract,
      this,
      options,
      "MinSwapCountUpdated",
      fromCount
    );
  }

  subscribeAllEvents(
    options: EventSubscribeOptions<
      | DexAccountRootTypes.OwnerUpdatedEvent
      | DexAccountRootTypes.ClmmParentSetEvent
      | DexAccountRootTypes.CpmmParentSetEvent
      | DexAccountRootTypes.MinSwapCountUpdatedEvent
    >,
    fromCount?: number
  ): EventSubscription {
    return subscribeContractEvents(
      DexAccountRoot.contract,
      this,
      options,
      fromCount
    );
  }

  view = {
    setCpmmParent: async (
      params: DexAccountRootTypes.CallMethodParams<"setCpmmParent">
    ): Promise<DexAccountRootTypes.CallMethodResult<"setCpmmParent">> => {
      return callMethod(
        DexAccountRoot,
        this,
        "setCpmmParent",
        params,
        getContractByCodeHash
      );
    },
    createAccount: async (
      params: DexAccountRootTypes.CallMethodParams<"createAccount">
    ): Promise<DexAccountRootTypes.CallMethodResult<"createAccount">> => {
      return callMethod(
        DexAccountRoot,
        this,
        "createAccount",
        params,
        getContractByCodeHash
      );
    },
    updateOwner: async (
      params: DexAccountRootTypes.CallMethodParams<"updateOwner">
    ): Promise<DexAccountRootTypes.CallMethodResult<"updateOwner">> => {
      return callMethod(
        DexAccountRoot,
        this,
        "updateOwner",
        params,
        getContractByCodeHash
      );
    },
    setClmmParent: async (
      params: DexAccountRootTypes.CallMethodParams<"setClmmParent">
    ): Promise<DexAccountRootTypes.CallMethodResult<"setClmmParent">> => {
      return callMethod(
        DexAccountRoot,
        this,
        "setClmmParent",
        params,
        getContractByCodeHash
      );
    },
    updateMinSwapCount: async (
      params: DexAccountRootTypes.CallMethodParams<"updateMinSwapCount">
    ): Promise<DexAccountRootTypes.CallMethodResult<"updateMinSwapCount">> => {
      return callMethod(
        DexAccountRoot,
        this,
        "updateMinSwapCount",
        params,
        getContractByCodeHash
      );
    },
    upgrade: async (
      params: DexAccountRootTypes.CallMethodParams<"upgrade">
    ): Promise<DexAccountRootTypes.CallMethodResult<"upgrade">> => {
      return callMethod(
        DexAccountRoot,
        this,
        "upgrade",
        params,
        getContractByCodeHash
      );
    },
    upgradeDexAccount: async (
      params: DexAccountRootTypes.CallMethodParams<"upgradeDexAccount">
    ): Promise<DexAccountRootTypes.CallMethodResult<"upgradeDexAccount">> => {
      return callMethod(
        DexAccountRoot,
        this,
        "upgradeDexAccount",
        params,
        getContractByCodeHash
      );
    },
  };

  transact = {
    setCpmmParent: async (
      params: DexAccountRootTypes.SignExecuteMethodParams<"setCpmmParent">
    ): Promise<
      DexAccountRootTypes.SignExecuteMethodResult<"setCpmmParent">
    > => {
      return signExecuteMethod(DexAccountRoot, this, "setCpmmParent", params);
    },
    createAccount: async (
      params: DexAccountRootTypes.SignExecuteMethodParams<"createAccount">
    ): Promise<
      DexAccountRootTypes.SignExecuteMethodResult<"createAccount">
    > => {
      return signExecuteMethod(DexAccountRoot, this, "createAccount", params);
    },
    updateOwner: async (
      params: DexAccountRootTypes.SignExecuteMethodParams<"updateOwner">
    ): Promise<DexAccountRootTypes.SignExecuteMethodResult<"updateOwner">> => {
      return signExecuteMethod(DexAccountRoot, this, "updateOwner", params);
    },
    setClmmParent: async (
      params: DexAccountRootTypes.SignExecuteMethodParams<"setClmmParent">
    ): Promise<
      DexAccountRootTypes.SignExecuteMethodResult<"setClmmParent">
    > => {
      return signExecuteMethod(DexAccountRoot, this, "setClmmParent", params);
    },
    updateMinSwapCount: async (
      params: DexAccountRootTypes.SignExecuteMethodParams<"updateMinSwapCount">
    ): Promise<
      DexAccountRootTypes.SignExecuteMethodResult<"updateMinSwapCount">
    > => {
      return signExecuteMethod(
        DexAccountRoot,
        this,
        "updateMinSwapCount",
        params
      );
    },
    upgrade: async (
      params: DexAccountRootTypes.SignExecuteMethodParams<"upgrade">
    ): Promise<DexAccountRootTypes.SignExecuteMethodResult<"upgrade">> => {
      return signExecuteMethod(DexAccountRoot, this, "upgrade", params);
    },
    upgradeDexAccount: async (
      params: DexAccountRootTypes.SignExecuteMethodParams<"upgradeDexAccount">
    ): Promise<
      DexAccountRootTypes.SignExecuteMethodResult<"upgradeDexAccount">
    > => {
      return signExecuteMethod(
        DexAccountRoot,
        this,
        "upgradeDexAccount",
        params
      );
    },
  };
}
