/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  Address,
  Contract,
  ContractState,
  TestContractResult,
  HexString,
  ContractFactory,
  EventSubscribeOptions,
  EventSubscription,
  CallContractParams,
  CallContractResult,
  TestContractParams,
  ContractEvent,
  subscribeContractEvent,
  subscribeContractEvents,
  testMethod,
  callMethod,
  multicallMethods,
  fetchContractState,
  Asset,
  ContractInstance,
  getContractEventsCurrentCount,
  TestContractParamsWithoutMaps,
  TestContractResultWithoutMaps,
  SignExecuteContractMethodParams,
  SignExecuteScriptTxResult,
  signExecuteMethod,
  addStdIdToFields,
  encodeContractFields,
  Narrow,
} from "@alephium/web3";
import { default as DexAccountContractJson } from "../DexAccount.ral.json";
import { getContractByCodeHash, registerContract } from "./contracts";
import {
  CollectParams,
  Config,
  DecreaseLiquidityParams,
  ModifyLiquidityParams,
  ModifyPositionParams,
  ProtocolFees,
  Reward,
  Slot0,
  StepComputations,
  SwapCache,
  SwapParams,
  SwapState,
  AllStructs,
} from "./types";

// Custom types for the contract
export namespace DexAccountTypes {
  export type Fields = {
    parent: HexString;
    owner: Address;
    refferer: Address;
    counter: bigint;
  };

  export type State = ContractState<Fields>;

  export interface CallMethodTable {
    deposit: {
      params: CallContractParams<{ tokenId: HexString; amount: bigint }>;
      result: CallContractResult<null>;
    };
    asRef: {
      params: CallContractParams<{ defaultRef: Address }>;
      result: CallContractResult<Address>;
    };
    refer: {
      params: CallContractParams<{ user: Address; ref: Address; n: bigint }>;
      result: CallContractResult<null>;
    };
  }
  export type CallMethodParams<T extends keyof CallMethodTable> =
    CallMethodTable[T]["params"];
  export type CallMethodResult<T extends keyof CallMethodTable> =
    CallMethodTable[T]["result"];
  export type MultiCallParams = Partial<{
    [Name in keyof CallMethodTable]: CallMethodTable[Name]["params"];
  }>;
  export type MultiCallResults<T extends MultiCallParams> = {
    [MaybeName in keyof T]: MaybeName extends keyof CallMethodTable
      ? CallMethodTable[MaybeName]["result"]
      : undefined;
  };
  export type MulticallReturnType<Callss extends MultiCallParams[]> = {
    [index in keyof Callss]: MultiCallResults<Callss[index]>;
  };

  export interface SignExecuteMethodTable {
    deposit: {
      params: SignExecuteContractMethodParams<{
        tokenId: HexString;
        amount: bigint;
      }>;
      result: SignExecuteScriptTxResult;
    };
    asRef: {
      params: SignExecuteContractMethodParams<{ defaultRef: Address }>;
      result: SignExecuteScriptTxResult;
    };
    refer: {
      params: SignExecuteContractMethodParams<{
        user: Address;
        ref: Address;
        n: bigint;
      }>;
      result: SignExecuteScriptTxResult;
    };
  }
  export type SignExecuteMethodParams<T extends keyof SignExecuteMethodTable> =
    SignExecuteMethodTable[T]["params"];
  export type SignExecuteMethodResult<T extends keyof SignExecuteMethodTable> =
    SignExecuteMethodTable[T]["result"];
}

class Factory extends ContractFactory<
  DexAccountInstance,
  DexAccountTypes.Fields
> {
  encodeFields(fields: DexAccountTypes.Fields) {
    return encodeContractFields(
      addStdIdToFields(this.contract, fields),
      this.contract.fieldsSig,
      AllStructs
    );
  }

  at(address: string): DexAccountInstance {
    return new DexAccountInstance(address);
  }

  tests = {
    deposit: async (
      params: TestContractParamsWithoutMaps<
        DexAccountTypes.Fields,
        { tokenId: HexString; amount: bigint }
      >
    ): Promise<TestContractResultWithoutMaps<null>> => {
      return testMethod(this, "deposit", params, getContractByCodeHash);
    },
    asRef: async (
      params: TestContractParamsWithoutMaps<
        DexAccountTypes.Fields,
        { defaultRef: Address }
      >
    ): Promise<TestContractResultWithoutMaps<Address>> => {
      return testMethod(this, "asRef", params, getContractByCodeHash);
    },
    refer: async (
      params: TestContractParamsWithoutMaps<
        DexAccountTypes.Fields,
        { user: Address; ref: Address; n: bigint }
      >
    ): Promise<TestContractResultWithoutMaps<null>> => {
      return testMethod(this, "refer", params, getContractByCodeHash);
    },
  };

  stateForTest(
    initFields: DexAccountTypes.Fields,
    asset?: Asset,
    address?: string
  ) {
    return this.stateForTest_(initFields, asset, address, undefined);
  }
}

// Use this object to test and deploy the contract
export const DexAccount = new Factory(
  Contract.fromJson(
    DexAccountContractJson,
    "",
    "76be29f13ad97873ef403efdd77837f6bbcb83d23e7a3bd8f6d15751f2b8abe8",
    AllStructs
  )
);
registerContract(DexAccount);

// Use this class to interact with the blockchain
export class DexAccountInstance extends ContractInstance {
  constructor(address: Address) {
    super(address);
  }

  async fetchState(): Promise<DexAccountTypes.State> {
    return fetchContractState(DexAccount, this);
  }

  view = {
    deposit: async (
      params: DexAccountTypes.CallMethodParams<"deposit">
    ): Promise<DexAccountTypes.CallMethodResult<"deposit">> => {
      return callMethod(
        DexAccount,
        this,
        "deposit",
        params,
        getContractByCodeHash
      );
    },
    asRef: async (
      params: DexAccountTypes.CallMethodParams<"asRef">
    ): Promise<DexAccountTypes.CallMethodResult<"asRef">> => {
      return callMethod(
        DexAccount,
        this,
        "asRef",
        params,
        getContractByCodeHash
      );
    },
    refer: async (
      params: DexAccountTypes.CallMethodParams<"refer">
    ): Promise<DexAccountTypes.CallMethodResult<"refer">> => {
      return callMethod(
        DexAccount,
        this,
        "refer",
        params,
        getContractByCodeHash
      );
    },
  };

  transact = {
    deposit: async (
      params: DexAccountTypes.SignExecuteMethodParams<"deposit">
    ): Promise<DexAccountTypes.SignExecuteMethodResult<"deposit">> => {
      return signExecuteMethod(DexAccount, this, "deposit", params);
    },
    asRef: async (
      params: DexAccountTypes.SignExecuteMethodParams<"asRef">
    ): Promise<DexAccountTypes.SignExecuteMethodResult<"asRef">> => {
      return signExecuteMethod(DexAccount, this, "asRef", params);
    },
    refer: async (
      params: DexAccountTypes.SignExecuteMethodParams<"refer">
    ): Promise<DexAccountTypes.SignExecuteMethodResult<"refer">> => {
      return signExecuteMethod(DexAccount, this, "refer", params);
    },
  };

  async multicall<Calls extends DexAccountTypes.MultiCallParams>(
    calls: Calls
  ): Promise<DexAccountTypes.MultiCallResults<Calls>>;
  async multicall<Callss extends DexAccountTypes.MultiCallParams[]>(
    callss: Narrow<Callss>
  ): Promise<DexAccountTypes.MulticallReturnType<Callss>>;
  async multicall<
    Callss extends
      | DexAccountTypes.MultiCallParams
      | DexAccountTypes.MultiCallParams[]
  >(callss: Callss): Promise<unknown> {
    return await multicallMethods(
      DexAccount,
      this,
      callss,
      getContractByCodeHash
    );
  }
}
