/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  Address,
  Contract,
  ContractState,
  TestContractResult,
  HexString,
  ContractFactory,
  EventSubscribeOptions,
  EventSubscription,
  CallContractParams,
  CallContractResult,
  TestContractParams,
  ContractEvent,
  subscribeContractEvent,
  subscribeContractEvents,
  testMethod,
  callMethod,
  multicallMethods,
  fetchContractState,
  Asset,
  ContractInstance,
  getContractEventsCurrentCount,
  TestContractParamsWithoutMaps,
  TestContractResultWithoutMaps,
  SignExecuteContractMethodParams,
  SignExecuteScriptTxResult,
  signExecuteMethod,
  addStdIdToFields,
  encodeContractFields,
  Narrow,
} from "@alephium/web3";
import { default as FakeClmmFactoryContractJson } from "../test/FakeClmmFactory.ral.json";
import { getContractByCodeHash, registerContract } from "./contracts";
import * as types from "./types";

// Custom types for the contract
export namespace FakeClmmFactoryTypes {
  export type Fields = {
    owner: Address;
    feeCollector: Address;
    poolTemplate: HexString;
    positionTemplate: HexString;
    tickTemplate: HexString;
    wordTemplate: HexString;
    poolConfigTemplate: HexString;
    dexAccountRoot: HexString;
    nextConfigIndex: bigint;
  };

  export type State = ContractState<Fields>;

  export interface CallMethodTable {
    doNothing: {
      params: Omit<CallContractParams<{}>, "args">;
      result: CallContractResult<HexString>;
    };
  }
  export type CallMethodParams<T extends keyof CallMethodTable> =
    CallMethodTable[T]["params"];
  export type CallMethodResult<T extends keyof CallMethodTable> =
    CallMethodTable[T]["result"];
  export type MultiCallParams = Partial<{
    [Name in keyof CallMethodTable]: CallMethodTable[Name]["params"];
  }>;
  export type MultiCallResults<T extends MultiCallParams> = {
    [MaybeName in keyof T]: MaybeName extends keyof CallMethodTable
      ? CallMethodTable[MaybeName]["result"]
      : undefined;
  };
  export type MulticallReturnType<Callss extends MultiCallParams[]> = {
    [index in keyof Callss]: MultiCallResults<Callss[index]>;
  };

  export interface SignExecuteMethodTable {
    doNothing: {
      params: Omit<SignExecuteContractMethodParams<{}>, "args">;
      result: SignExecuteScriptTxResult;
    };
  }
  export type SignExecuteMethodParams<T extends keyof SignExecuteMethodTable> =
    SignExecuteMethodTable[T]["params"];
  export type SignExecuteMethodResult<T extends keyof SignExecuteMethodTable> =
    SignExecuteMethodTable[T]["result"];
}

class Factory extends ContractFactory<
  FakeClmmFactoryInstance,
  FakeClmmFactoryTypes.Fields
> {
  encodeFields(fields: FakeClmmFactoryTypes.Fields) {
    return encodeContractFields(
      addStdIdToFields(this.contract, fields),
      this.contract.fieldsSig,
      types.AllStructs
    );
  }

  at(address: string): FakeClmmFactoryInstance {
    return new FakeClmmFactoryInstance(address);
  }

  tests = {
    doNothing: async (
      params: Omit<
        TestContractParamsWithoutMaps<FakeClmmFactoryTypes.Fields, never>,
        "args"
      >
    ): Promise<TestContractResultWithoutMaps<HexString>> => {
      return testMethod(this, "doNothing", params, getContractByCodeHash);
    },
  };

  stateForTest(
    initFields: FakeClmmFactoryTypes.Fields,
    asset?: Asset,
    address?: string
  ) {
    return this.stateForTest_(initFields, asset, address, undefined);
  }
}

// Use this object to test and deploy the contract
export const FakeClmmFactory = new Factory(
  Contract.fromJson(
    FakeClmmFactoryContractJson,
    "",
    "7d3c5ae61ed0619017b7eb22687a55b43ee6fc28da9955ee0cbef241e2a40717",
    types.AllStructs
  )
);
registerContract(FakeClmmFactory);

// Use this class to interact with the blockchain
export class FakeClmmFactoryInstance extends ContractInstance {
  constructor(address: Address) {
    super(address);
  }

  async fetchState(): Promise<FakeClmmFactoryTypes.State> {
    return fetchContractState(FakeClmmFactory, this);
  }

  view = {
    doNothing: async (
      params?: FakeClmmFactoryTypes.CallMethodParams<"doNothing">
    ): Promise<FakeClmmFactoryTypes.CallMethodResult<"doNothing">> => {
      return callMethod(
        FakeClmmFactory,
        this,
        "doNothing",
        params === undefined ? {} : params,
        getContractByCodeHash
      );
    },
  };

  transact = {
    doNothing: async (
      params: FakeClmmFactoryTypes.SignExecuteMethodParams<"doNothing">
    ): Promise<FakeClmmFactoryTypes.SignExecuteMethodResult<"doNothing">> => {
      return signExecuteMethod(FakeClmmFactory, this, "doNothing", params);
    },
  };

  async multicall<Calls extends FakeClmmFactoryTypes.MultiCallParams>(
    calls: Calls
  ): Promise<FakeClmmFactoryTypes.MultiCallResults<Calls>>;
  async multicall<Callss extends FakeClmmFactoryTypes.MultiCallParams[]>(
    callss: Narrow<Callss>
  ): Promise<FakeClmmFactoryTypes.MulticallReturnType<Callss>>;
  async multicall<
    Callss extends
      | FakeClmmFactoryTypes.MultiCallParams
      | FakeClmmFactoryTypes.MultiCallParams[]
  >(callss: Callss): Promise<unknown> {
    return await multicallMethods(
      FakeClmmFactory,
      this,
      callss,
      getContractByCodeHash
    );
  }
}
