/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  Address,
  Contract,
  ContractState,
  TestContractResult,
  HexString,
  ContractFactory,
  EventSubscribeOptions,
  EventSubscription,
  CallContractParams,
  CallContractResult,
  TestContractParams,
  ContractEvent,
  subscribeContractEvent,
  subscribeContractEvents,
  testMethod,
  callMethod,
  multicallMethods,
  fetchContractState,
  Asset,
  ContractInstance,
  getContractEventsCurrentCount,
  TestContractParamsWithoutMaps,
  TestContractResultWithoutMaps,
  SignExecuteContractMethodParams,
  SignExecuteScriptTxResult,
  signExecuteMethod,
  addStdIdToFields,
  encodeContractFields,
  Narrow,
} from "@alephium/web3";
import { default as FuzzChildContractJson } from "../test/FuzzChild.ral.json";
import { getContractByCodeHash, registerContract } from "./contracts";
import * as types from "./types";

// Custom types for the contract
export namespace FuzzChildTypes {
  export type State = Omit<ContractState<any>, "fields">;

  export interface CallMethodTable {
    collect: {
      params: CallContractParams<{ force: boolean; amount: bigint }>;
      result: CallContractResult<null>;
    };
    withdraw: {
      params: CallContractParams<{ force: boolean; amount: bigint }>;
      result: CallContractResult<null>;
    };
    get: {
      params: Omit<CallContractParams<{}>, "args">;
      result: CallContractResult<bigint>;
    };
  }
  export type CallMethodParams<T extends keyof CallMethodTable> =
    CallMethodTable[T]["params"];
  export type CallMethodResult<T extends keyof CallMethodTable> =
    CallMethodTable[T]["result"];
  export type MultiCallParams = Partial<{
    [Name in keyof CallMethodTable]: CallMethodTable[Name]["params"];
  }>;
  export type MultiCallResults<T extends MultiCallParams> = {
    [MaybeName in keyof T]: MaybeName extends keyof CallMethodTable
      ? CallMethodTable[MaybeName]["result"]
      : undefined;
  };
  export type MulticallReturnType<Callss extends MultiCallParams[]> = {
    [index in keyof Callss]: MultiCallResults<Callss[index]>;
  };

  export interface SignExecuteMethodTable {
    collect: {
      params: SignExecuteContractMethodParams<{
        force: boolean;
        amount: bigint;
      }>;
      result: SignExecuteScriptTxResult;
    };
    withdraw: {
      params: SignExecuteContractMethodParams<{
        force: boolean;
        amount: bigint;
      }>;
      result: SignExecuteScriptTxResult;
    };
    get: {
      params: Omit<SignExecuteContractMethodParams<{}>, "args">;
      result: SignExecuteScriptTxResult;
    };
  }
  export type SignExecuteMethodParams<T extends keyof SignExecuteMethodTable> =
    SignExecuteMethodTable[T]["params"];
  export type SignExecuteMethodResult<T extends keyof SignExecuteMethodTable> =
    SignExecuteMethodTable[T]["result"];
}

class Factory extends ContractFactory<FuzzChildInstance, {}> {
  encodeFields() {
    return encodeContractFields({}, this.contract.fieldsSig, types.AllStructs);
  }

  at(address: string): FuzzChildInstance {
    return new FuzzChildInstance(address);
  }

  tests = {
    collect: async (
      params: Omit<
        TestContractParamsWithoutMaps<
          never,
          { force: boolean; amount: bigint }
        >,
        "initialFields"
      >
    ): Promise<TestContractResultWithoutMaps<null>> => {
      return testMethod(this, "collect", params, getContractByCodeHash);
    },
    withdraw: async (
      params: Omit<
        TestContractParamsWithoutMaps<
          never,
          { force: boolean; amount: bigint }
        >,
        "initialFields"
      >
    ): Promise<TestContractResultWithoutMaps<null>> => {
      return testMethod(this, "withdraw", params, getContractByCodeHash);
    },
    get: async (
      params?: Omit<
        TestContractParamsWithoutMaps<never, never>,
        "args" | "initialFields"
      >
    ): Promise<TestContractResultWithoutMaps<bigint>> => {
      return testMethod(
        this,
        "get",
        params === undefined ? {} : params,
        getContractByCodeHash
      );
    },
  };

  stateForTest(initFields: {}, asset?: Asset, address?: string) {
    return this.stateForTest_(initFields, asset, address, undefined);
  }
}

// Use this object to test and deploy the contract
export const FuzzChild = new Factory(
  Contract.fromJson(
    FuzzChildContractJson,
    "",
    "bae59690e7014ecfc251734667b18f1af735776bd16c18db6e886cd8ebcb1330",
    types.AllStructs
  )
);
registerContract(FuzzChild);

// Use this class to interact with the blockchain
export class FuzzChildInstance extends ContractInstance {
  constructor(address: Address) {
    super(address);
  }

  async fetchState(): Promise<FuzzChildTypes.State> {
    return fetchContractState(FuzzChild, this);
  }

  view = {
    collect: async (
      params: FuzzChildTypes.CallMethodParams<"collect">
    ): Promise<FuzzChildTypes.CallMethodResult<"collect">> => {
      return callMethod(
        FuzzChild,
        this,
        "collect",
        params,
        getContractByCodeHash
      );
    },
    withdraw: async (
      params: FuzzChildTypes.CallMethodParams<"withdraw">
    ): Promise<FuzzChildTypes.CallMethodResult<"withdraw">> => {
      return callMethod(
        FuzzChild,
        this,
        "withdraw",
        params,
        getContractByCodeHash
      );
    },
    get: async (
      params?: FuzzChildTypes.CallMethodParams<"get">
    ): Promise<FuzzChildTypes.CallMethodResult<"get">> => {
      return callMethod(
        FuzzChild,
        this,
        "get",
        params === undefined ? {} : params,
        getContractByCodeHash
      );
    },
  };

  transact = {
    collect: async (
      params: FuzzChildTypes.SignExecuteMethodParams<"collect">
    ): Promise<FuzzChildTypes.SignExecuteMethodResult<"collect">> => {
      return signExecuteMethod(FuzzChild, this, "collect", params);
    },
    withdraw: async (
      params: FuzzChildTypes.SignExecuteMethodParams<"withdraw">
    ): Promise<FuzzChildTypes.SignExecuteMethodResult<"withdraw">> => {
      return signExecuteMethod(FuzzChild, this, "withdraw", params);
    },
    get: async (
      params: FuzzChildTypes.SignExecuteMethodParams<"get">
    ): Promise<FuzzChildTypes.SignExecuteMethodResult<"get">> => {
      return signExecuteMethod(FuzzChild, this, "get", params);
    },
  };

  async multicall<Calls extends FuzzChildTypes.MultiCallParams>(
    calls: Calls
  ): Promise<FuzzChildTypes.MultiCallResults<Calls>>;
  async multicall<Callss extends FuzzChildTypes.MultiCallParams[]>(
    callss: Narrow<Callss>
  ): Promise<FuzzChildTypes.MulticallReturnType<Callss>>;
  async multicall<
    Callss extends
      | FuzzChildTypes.MultiCallParams
      | FuzzChildTypes.MultiCallParams[]
  >(callss: Callss): Promise<unknown> {
    return await multicallMethods(
      FuzzChild,
      this,
      callss,
      getContractByCodeHash
    );
  }
}
