/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  Address,
  Contract,
  ContractState,
  TestContractResult,
  HexString,
  ContractFactory,
  EventSubscribeOptions,
  EventSubscription,
  CallContractParams,
  CallContractResult,
  TestContractParams,
  ContractEvent,
  subscribeContractEvent,
  subscribeContractEvents,
  testMethod,
  callMethod,
  multicallMethods,
  fetchContractState,
  Asset,
  ContractInstance,
  getContractEventsCurrentCount,
  TestContractParamsWithoutMaps,
  TestContractResultWithoutMaps,
  SignExecuteContractMethodParams,
  SignExecuteScriptTxResult,
  signExecuteMethod,
  addStdIdToFields,
  encodeContractFields,
  Narrow,
} from "@alephium/web3";
import { default as FuzzPoolContractJson } from "../test/FuzzPool.ral.json";
import { getContractByCodeHash, registerContract } from "./contracts";
import * as types from "./types";

// Custom types for the contract
export namespace FuzzPoolTypes {
  export type Fields = {
    owner: Address;
    tLower: bigint;
    tUpper: bigint;
  };

  export type State = ContractState<Fields>;

  export interface CallMethodTable {
    positionPath: {
      params: CallContractParams<{
        o: Address;
        tickLower: bigint;
        tickUpper: bigint;
      }>;
      result: CallContractResult<HexString>;
    };
    positionContractId: {
      params: CallContractParams<{
        pool: HexString;
        o: Address;
        tickLower: bigint;
        tickUpper: bigint;
      }>;
      result: CallContractResult<HexString>;
    };
    burnAndCollect: {
      params: CallContractParams<{ pool: HexString }>;
      result: CallContractResult<null>;
    };
  }
  export type CallMethodParams<T extends keyof CallMethodTable> =
    CallMethodTable[T]["params"];
  export type CallMethodResult<T extends keyof CallMethodTable> =
    CallMethodTable[T]["result"];
  export type MultiCallParams = Partial<{
    [Name in keyof CallMethodTable]: CallMethodTable[Name]["params"];
  }>;
  export type MultiCallResults<T extends MultiCallParams> = {
    [MaybeName in keyof T]: MaybeName extends keyof CallMethodTable
      ? CallMethodTable[MaybeName]["result"]
      : undefined;
  };
  export type MulticallReturnType<Callss extends MultiCallParams[]> = {
    [index in keyof Callss]: MultiCallResults<Callss[index]>;
  };

  export interface SignExecuteMethodTable {
    positionPath: {
      params: SignExecuteContractMethodParams<{
        o: Address;
        tickLower: bigint;
        tickUpper: bigint;
      }>;
      result: SignExecuteScriptTxResult;
    };
    positionContractId: {
      params: SignExecuteContractMethodParams<{
        pool: HexString;
        o: Address;
        tickLower: bigint;
        tickUpper: bigint;
      }>;
      result: SignExecuteScriptTxResult;
    };
    burnAndCollect: {
      params: SignExecuteContractMethodParams<{ pool: HexString }>;
      result: SignExecuteScriptTxResult;
    };
  }
  export type SignExecuteMethodParams<T extends keyof SignExecuteMethodTable> =
    SignExecuteMethodTable[T]["params"];
  export type SignExecuteMethodResult<T extends keyof SignExecuteMethodTable> =
    SignExecuteMethodTable[T]["result"];
}

class Factory extends ContractFactory<FuzzPoolInstance, FuzzPoolTypes.Fields> {
  encodeFields(fields: FuzzPoolTypes.Fields) {
    return encodeContractFields(
      addStdIdToFields(this.contract, fields),
      this.contract.fieldsSig,
      types.AllStructs
    );
  }

  consts = {
    PathPrefixes: {
      Tick: BigInt("0"),
      Position: BigInt("1"),
      Word: BigInt("2"),
    },
  };

  at(address: string): FuzzPoolInstance {
    return new FuzzPoolInstance(address);
  }

  tests = {
    positionPath: async (
      params: TestContractParamsWithoutMaps<
        FuzzPoolTypes.Fields,
        { o: Address; tickLower: bigint; tickUpper: bigint }
      >
    ): Promise<TestContractResultWithoutMaps<HexString>> => {
      return testMethod(this, "positionPath", params, getContractByCodeHash);
    },
    positionContractId: async (
      params: TestContractParamsWithoutMaps<
        FuzzPoolTypes.Fields,
        { pool: HexString; o: Address; tickLower: bigint; tickUpper: bigint }
      >
    ): Promise<TestContractResultWithoutMaps<HexString>> => {
      return testMethod(
        this,
        "positionContractId",
        params,
        getContractByCodeHash
      );
    },
    burnAndCollect: async (
      params: TestContractParamsWithoutMaps<
        FuzzPoolTypes.Fields,
        { pool: HexString }
      >
    ): Promise<TestContractResultWithoutMaps<null>> => {
      return testMethod(this, "burnAndCollect", params, getContractByCodeHash);
    },
  };

  stateForTest(
    initFields: FuzzPoolTypes.Fields,
    asset?: Asset,
    address?: string
  ) {
    return this.stateForTest_(initFields, asset, address, undefined);
  }
}

// Use this object to test and deploy the contract
export const FuzzPool = new Factory(
  Contract.fromJson(
    FuzzPoolContractJson,
    "",
    "e4b9a2d187385e4f677836f9356e290234c300898bac3d67a96b05542655028c",
    types.AllStructs
  )
);
registerContract(FuzzPool);

// Use this class to interact with the blockchain
export class FuzzPoolInstance extends ContractInstance {
  constructor(address: Address) {
    super(address);
  }

  async fetchState(): Promise<FuzzPoolTypes.State> {
    return fetchContractState(FuzzPool, this);
  }

  view = {
    positionPath: async (
      params: FuzzPoolTypes.CallMethodParams<"positionPath">
    ): Promise<FuzzPoolTypes.CallMethodResult<"positionPath">> => {
      return callMethod(
        FuzzPool,
        this,
        "positionPath",
        params,
        getContractByCodeHash
      );
    },
    positionContractId: async (
      params: FuzzPoolTypes.CallMethodParams<"positionContractId">
    ): Promise<FuzzPoolTypes.CallMethodResult<"positionContractId">> => {
      return callMethod(
        FuzzPool,
        this,
        "positionContractId",
        params,
        getContractByCodeHash
      );
    },
    burnAndCollect: async (
      params: FuzzPoolTypes.CallMethodParams<"burnAndCollect">
    ): Promise<FuzzPoolTypes.CallMethodResult<"burnAndCollect">> => {
      return callMethod(
        FuzzPool,
        this,
        "burnAndCollect",
        params,
        getContractByCodeHash
      );
    },
  };

  transact = {
    positionPath: async (
      params: FuzzPoolTypes.SignExecuteMethodParams<"positionPath">
    ): Promise<FuzzPoolTypes.SignExecuteMethodResult<"positionPath">> => {
      return signExecuteMethod(FuzzPool, this, "positionPath", params);
    },
    positionContractId: async (
      params: FuzzPoolTypes.SignExecuteMethodParams<"positionContractId">
    ): Promise<FuzzPoolTypes.SignExecuteMethodResult<"positionContractId">> => {
      return signExecuteMethod(FuzzPool, this, "positionContractId", params);
    },
    burnAndCollect: async (
      params: FuzzPoolTypes.SignExecuteMethodParams<"burnAndCollect">
    ): Promise<FuzzPoolTypes.SignExecuteMethodResult<"burnAndCollect">> => {
      return signExecuteMethod(FuzzPool, this, "burnAndCollect", params);
    },
  };

  async multicall<Calls extends FuzzPoolTypes.MultiCallParams>(
    calls: Calls
  ): Promise<FuzzPoolTypes.MultiCallResults<Calls>>;
  async multicall<Callss extends FuzzPoolTypes.MultiCallParams[]>(
    callss: Narrow<Callss>
  ): Promise<FuzzPoolTypes.MulticallReturnType<Callss>>;
  async multicall<
    Callss extends
      | FuzzPoolTypes.MultiCallParams
      | FuzzPoolTypes.MultiCallParams[]
  >(callss: Callss): Promise<unknown> {
    return await multicallMethods(
      FuzzPool,
      this,
      callss,
      getContractByCodeHash
    );
  }
}
