/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  Address,
  Contract,
  ContractState,
  TestContractResult,
  HexString,
  ContractFactory,
  EventSubscribeOptions,
  EventSubscription,
  CallContractParams,
  CallContractResult,
  TestContractParams,
  ContractEvent,
  subscribeContractEvent,
  subscribeContractEvents,
  testMethod,
  callMethod,
  multicallMethods,
  fetchContractState,
  Asset,
  ContractInstance,
  getContractEventsCurrentCount,
  TestContractParamsWithoutMaps,
  TestContractResultWithoutMaps,
  SignExecuteContractMethodParams,
  SignExecuteScriptTxResult,
  signExecuteMethod,
  addStdIdToFields,
  encodeContractFields,
  Narrow,
} from "@alephium/web3";
import { default as FuzzParentContractJson } from "../test/FuzzParent.ral.json";
import { getContractByCodeHash, registerContract } from "./contracts";
import * as types from "./types";

// Custom types for the contract
export namespace FuzzParentTypes {
  export type Fields = {
    id: HexString;
  };

  export type State = ContractState<Fields>;

  export interface CallMethodTable {
    create: {
      params: Omit<CallContractParams<{}>, "args">;
      result: CallContractResult<HexString>;
    };
    deposit: {
      params: CallContractParams<{ child: HexString }>;
      result: CallContractResult<null>;
    };
    collect: {
      params: CallContractParams<{ force: boolean; amount: bigint }>;
      result: CallContractResult<null>;
    };
    get: {
      params: Omit<CallContractParams<{}>, "args">;
      result: CallContractResult<[bigint, bigint]>;
    };
  }
  export type CallMethodParams<T extends keyof CallMethodTable> =
    CallMethodTable[T]["params"];
  export type CallMethodResult<T extends keyof CallMethodTable> =
    CallMethodTable[T]["result"];
  export type MultiCallParams = Partial<{
    [Name in keyof CallMethodTable]: CallMethodTable[Name]["params"];
  }>;
  export type MultiCallResults<T extends MultiCallParams> = {
    [MaybeName in keyof T]: MaybeName extends keyof CallMethodTable
      ? CallMethodTable[MaybeName]["result"]
      : undefined;
  };
  export type MulticallReturnType<Callss extends MultiCallParams[]> = {
    [index in keyof Callss]: MultiCallResults<Callss[index]>;
  };

  export interface SignExecuteMethodTable {
    create: {
      params: Omit<SignExecuteContractMethodParams<{}>, "args">;
      result: SignExecuteScriptTxResult;
    };
    deposit: {
      params: SignExecuteContractMethodParams<{ child: HexString }>;
      result: SignExecuteScriptTxResult;
    };
    collect: {
      params: SignExecuteContractMethodParams<{
        force: boolean;
        amount: bigint;
      }>;
      result: SignExecuteScriptTxResult;
    };
    get: {
      params: Omit<SignExecuteContractMethodParams<{}>, "args">;
      result: SignExecuteScriptTxResult;
    };
  }
  export type SignExecuteMethodParams<T extends keyof SignExecuteMethodTable> =
    SignExecuteMethodTable[T]["params"];
  export type SignExecuteMethodResult<T extends keyof SignExecuteMethodTable> =
    SignExecuteMethodTable[T]["result"];
}

class Factory extends ContractFactory<
  FuzzParentInstance,
  FuzzParentTypes.Fields
> {
  encodeFields(fields: FuzzParentTypes.Fields) {
    return encodeContractFields(
      addStdIdToFields(this.contract, fields),
      this.contract.fieldsSig,
      types.AllStructs
    );
  }

  at(address: string): FuzzParentInstance {
    return new FuzzParentInstance(address);
  }

  tests = {
    create: async (
      params: Omit<
        TestContractParamsWithoutMaps<FuzzParentTypes.Fields, never>,
        "args"
      >
    ): Promise<TestContractResultWithoutMaps<HexString>> => {
      return testMethod(this, "create", params, getContractByCodeHash);
    },
    deposit: async (
      params: TestContractParamsWithoutMaps<
        FuzzParentTypes.Fields,
        { child: HexString }
      >
    ): Promise<TestContractResultWithoutMaps<null>> => {
      return testMethod(this, "deposit", params, getContractByCodeHash);
    },
    collect: async (
      params: TestContractParamsWithoutMaps<
        FuzzParentTypes.Fields,
        { force: boolean; amount: bigint }
      >
    ): Promise<TestContractResultWithoutMaps<null>> => {
      return testMethod(this, "collect", params, getContractByCodeHash);
    },
    get: async (
      params: Omit<
        TestContractParamsWithoutMaps<FuzzParentTypes.Fields, never>,
        "args"
      >
    ): Promise<TestContractResultWithoutMaps<[bigint, bigint]>> => {
      return testMethod(this, "get", params, getContractByCodeHash);
    },
  };

  stateForTest(
    initFields: FuzzParentTypes.Fields,
    asset?: Asset,
    address?: string
  ) {
    return this.stateForTest_(initFields, asset, address, undefined);
  }
}

// Use this object to test and deploy the contract
export const FuzzParent = new Factory(
  Contract.fromJson(
    FuzzParentContractJson,
    "",
    "bdd965bc7b59474a4d9f902f0cceaddaadfc2bd2b9a323e49987a7df8df1db45",
    types.AllStructs
  )
);
registerContract(FuzzParent);

// Use this class to interact with the blockchain
export class FuzzParentInstance extends ContractInstance {
  constructor(address: Address) {
    super(address);
  }

  async fetchState(): Promise<FuzzParentTypes.State> {
    return fetchContractState(FuzzParent, this);
  }

  view = {
    create: async (
      params?: FuzzParentTypes.CallMethodParams<"create">
    ): Promise<FuzzParentTypes.CallMethodResult<"create">> => {
      return callMethod(
        FuzzParent,
        this,
        "create",
        params === undefined ? {} : params,
        getContractByCodeHash
      );
    },
    deposit: async (
      params: FuzzParentTypes.CallMethodParams<"deposit">
    ): Promise<FuzzParentTypes.CallMethodResult<"deposit">> => {
      return callMethod(
        FuzzParent,
        this,
        "deposit",
        params,
        getContractByCodeHash
      );
    },
    collect: async (
      params: FuzzParentTypes.CallMethodParams<"collect">
    ): Promise<FuzzParentTypes.CallMethodResult<"collect">> => {
      return callMethod(
        FuzzParent,
        this,
        "collect",
        params,
        getContractByCodeHash
      );
    },
    get: async (
      params?: FuzzParentTypes.CallMethodParams<"get">
    ): Promise<FuzzParentTypes.CallMethodResult<"get">> => {
      return callMethod(
        FuzzParent,
        this,
        "get",
        params === undefined ? {} : params,
        getContractByCodeHash
      );
    },
  };

  transact = {
    create: async (
      params: FuzzParentTypes.SignExecuteMethodParams<"create">
    ): Promise<FuzzParentTypes.SignExecuteMethodResult<"create">> => {
      return signExecuteMethod(FuzzParent, this, "create", params);
    },
    deposit: async (
      params: FuzzParentTypes.SignExecuteMethodParams<"deposit">
    ): Promise<FuzzParentTypes.SignExecuteMethodResult<"deposit">> => {
      return signExecuteMethod(FuzzParent, this, "deposit", params);
    },
    collect: async (
      params: FuzzParentTypes.SignExecuteMethodParams<"collect">
    ): Promise<FuzzParentTypes.SignExecuteMethodResult<"collect">> => {
      return signExecuteMethod(FuzzParent, this, "collect", params);
    },
    get: async (
      params: FuzzParentTypes.SignExecuteMethodParams<"get">
    ): Promise<FuzzParentTypes.SignExecuteMethodResult<"get">> => {
      return signExecuteMethod(FuzzParent, this, "get", params);
    },
  };

  async multicall<Calls extends FuzzParentTypes.MultiCallParams>(
    calls: Calls
  ): Promise<FuzzParentTypes.MultiCallResults<Calls>>;
  async multicall<Callss extends FuzzParentTypes.MultiCallParams[]>(
    callss: Narrow<Callss>
  ): Promise<FuzzParentTypes.MulticallReturnType<Callss>>;
  async multicall<
    Callss extends
      | FuzzParentTypes.MultiCallParams
      | FuzzParentTypes.MultiCallParams[]
  >(callss: Callss): Promise<unknown> {
    return await multicallMethods(
      FuzzParent,
      this,
      callss,
      getContractByCodeHash
    );
  }
}
