/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  Address,
  Contract,
  ContractState,
  TestContractResult,
  HexString,
  ContractFactory,
  EventSubscribeOptions,
  EventSubscription,
  CallContractParams,
  CallContractResult,
  TestContractParams,
  ContractEvent,
  subscribeContractEvent,
  subscribeContractEvents,
  testMethod,
  callMethod,
  multicallMethods,
  fetchContractState,
  Asset,
  ContractInstance,
  getContractEventsCurrentCount,
  TestContractParamsWithoutMaps,
  TestContractResultWithoutMaps,
  SignExecuteContractMethodParams,
  SignExecuteScriptTxResult,
  signExecuteMethod,
  addStdIdToFields,
  encodeContractFields,
  Narrow,
} from "@alephium/web3";
import { default as FuzzPositionContractJson } from "../test/FuzzPosition.ral.json";
import { getContractByCodeHash, registerContract } from "./contracts";
import * as types from "./types";

// Custom types for the contract
export namespace FuzzPositionTypes {
  export type Fields = {
    owner: Address;
    tickLower0: bigint;
    tickUpper0: bigint;
    liquidity: bigint;
    collecting: bigint;
  };

  export type State = ContractState<Fields>;

  export interface CallMethodTable {
    getSqrtRatioAtTick: {
      params: CallContractParams<{ tick: bigint }>;
      result: CallContractResult<bigint>;
    };
    getTickAtSqrtRatio: {
      params: CallContractParams<{ sqrtPriceX96: bigint }>;
      result: CallContractResult<bigint>;
    };
    positionPath: {
      params: CallContractParams<{
        o: Address;
        tickLower: bigint;
        tickUpper: bigint;
      }>;
      result: CallContractResult<HexString>;
    };
    positionContractId: {
      params: CallContractParams<{
        pool: HexString;
        o: Address;
        tickLower: bigint;
        tickUpper: bigint;
      }>;
      result: CallContractResult<HexString>;
    };
    step: {
      params: CallContractParams<{
        x: bigint;
        seed: bigint;
        pool: HexString;
        token0: HexString;
        token1: HexString;
      }>;
      result: CallContractResult<[bigint, HexString]>;
    };
    deposit: {
      params: CallContractParams<{
        payer: Address;
        x: bigint;
        token: HexString;
        amount: bigint;
      }>;
      result: CallContractResult<null>;
    };
    burnAndCollect: {
      params: CallContractParams<{ pool: HexString }>;
      result: CallContractResult<null>;
    };
  }
  export type CallMethodParams<T extends keyof CallMethodTable> =
    CallMethodTable[T]["params"];
  export type CallMethodResult<T extends keyof CallMethodTable> =
    CallMethodTable[T]["result"];
  export type MultiCallParams = Partial<{
    [Name in keyof CallMethodTable]: CallMethodTable[Name]["params"];
  }>;
  export type MultiCallResults<T extends MultiCallParams> = {
    [MaybeName in keyof T]: MaybeName extends keyof CallMethodTable
      ? CallMethodTable[MaybeName]["result"]
      : undefined;
  };
  export type MulticallReturnType<Callss extends MultiCallParams[]> = {
    [index in keyof Callss]: MultiCallResults<Callss[index]>;
  };

  export interface SignExecuteMethodTable {
    getSqrtRatioAtTick: {
      params: SignExecuteContractMethodParams<{ tick: bigint }>;
      result: SignExecuteScriptTxResult;
    };
    getTickAtSqrtRatio: {
      params: SignExecuteContractMethodParams<{ sqrtPriceX96: bigint }>;
      result: SignExecuteScriptTxResult;
    };
    positionPath: {
      params: SignExecuteContractMethodParams<{
        o: Address;
        tickLower: bigint;
        tickUpper: bigint;
      }>;
      result: SignExecuteScriptTxResult;
    };
    positionContractId: {
      params: SignExecuteContractMethodParams<{
        pool: HexString;
        o: Address;
        tickLower: bigint;
        tickUpper: bigint;
      }>;
      result: SignExecuteScriptTxResult;
    };
    step: {
      params: SignExecuteContractMethodParams<{
        x: bigint;
        seed: bigint;
        pool: HexString;
        token0: HexString;
        token1: HexString;
      }>;
      result: SignExecuteScriptTxResult;
    };
    deposit: {
      params: SignExecuteContractMethodParams<{
        payer: Address;
        x: bigint;
        token: HexString;
        amount: bigint;
      }>;
      result: SignExecuteScriptTxResult;
    };
    burnAndCollect: {
      params: SignExecuteContractMethodParams<{ pool: HexString }>;
      result: SignExecuteScriptTxResult;
    };
  }
  export type SignExecuteMethodParams<T extends keyof SignExecuteMethodTable> =
    SignExecuteMethodTable[T]["params"];
  export type SignExecuteMethodResult<T extends keyof SignExecuteMethodTable> =
    SignExecuteMethodTable[T]["result"];
}

class Factory extends ContractFactory<
  FuzzPositionInstance,
  FuzzPositionTypes.Fields
> {
  encodeFields(fields: FuzzPositionTypes.Fields) {
    return encodeContractFields(
      addStdIdToFields(this.contract, fields),
      this.contract.fieldsSig,
      types.AllStructs
    );
  }

  consts = {
    TickMathError: {
      SqrtPriceX96OutOfBounds: BigInt("201"),
      TickOutOfBounds: BigInt("202"),
    },
    PathPrefixes: {
      Tick: BigInt("0"),
      Position: BigInt("1"),
      Word: BigInt("2"),
    },
  };

  at(address: string): FuzzPositionInstance {
    return new FuzzPositionInstance(address);
  }

  tests = {
    getSqrtRatioAtTick: async (
      params: TestContractParamsWithoutMaps<
        FuzzPositionTypes.Fields,
        { tick: bigint }
      >
    ): Promise<TestContractResultWithoutMaps<bigint>> => {
      return testMethod(
        this,
        "getSqrtRatioAtTick",
        params,
        getContractByCodeHash
      );
    },
    getTickAtSqrtRatio: async (
      params: TestContractParamsWithoutMaps<
        FuzzPositionTypes.Fields,
        { sqrtPriceX96: bigint }
      >
    ): Promise<TestContractResultWithoutMaps<bigint>> => {
      return testMethod(
        this,
        "getTickAtSqrtRatio",
        params,
        getContractByCodeHash
      );
    },
    positionPath: async (
      params: TestContractParamsWithoutMaps<
        FuzzPositionTypes.Fields,
        { o: Address; tickLower: bigint; tickUpper: bigint }
      >
    ): Promise<TestContractResultWithoutMaps<HexString>> => {
      return testMethod(this, "positionPath", params, getContractByCodeHash);
    },
    positionContractId: async (
      params: TestContractParamsWithoutMaps<
        FuzzPositionTypes.Fields,
        { pool: HexString; o: Address; tickLower: bigint; tickUpper: bigint }
      >
    ): Promise<TestContractResultWithoutMaps<HexString>> => {
      return testMethod(
        this,
        "positionContractId",
        params,
        getContractByCodeHash
      );
    },
    step: async (
      params: TestContractParamsWithoutMaps<
        FuzzPositionTypes.Fields,
        {
          x: bigint;
          seed: bigint;
          pool: HexString;
          token0: HexString;
          token1: HexString;
        }
      >
    ): Promise<TestContractResultWithoutMaps<[bigint, HexString]>> => {
      return testMethod(this, "step", params, getContractByCodeHash);
    },
    deposit: async (
      params: TestContractParamsWithoutMaps<
        FuzzPositionTypes.Fields,
        { payer: Address; x: bigint; token: HexString; amount: bigint }
      >
    ): Promise<TestContractResultWithoutMaps<null>> => {
      return testMethod(this, "deposit", params, getContractByCodeHash);
    },
    burnAndCollect: async (
      params: TestContractParamsWithoutMaps<
        FuzzPositionTypes.Fields,
        { pool: HexString }
      >
    ): Promise<TestContractResultWithoutMaps<null>> => {
      return testMethod(this, "burnAndCollect", params, getContractByCodeHash);
    },
  };

  stateForTest(
    initFields: FuzzPositionTypes.Fields,
    asset?: Asset,
    address?: string
  ) {
    return this.stateForTest_(initFields, asset, address, undefined);
  }
}

// Use this object to test and deploy the contract
export const FuzzPosition = new Factory(
  Contract.fromJson(
    FuzzPositionContractJson,
    "",
    "03645726c507f9339ce4ce0457d67d1b670e5b42a3e42483210a2af29242c13e",
    types.AllStructs
  )
);
registerContract(FuzzPosition);

// Use this class to interact with the blockchain
export class FuzzPositionInstance extends ContractInstance {
  constructor(address: Address) {
    super(address);
  }

  async fetchState(): Promise<FuzzPositionTypes.State> {
    return fetchContractState(FuzzPosition, this);
  }

  view = {
    getSqrtRatioAtTick: async (
      params: FuzzPositionTypes.CallMethodParams<"getSqrtRatioAtTick">
    ): Promise<FuzzPositionTypes.CallMethodResult<"getSqrtRatioAtTick">> => {
      return callMethod(
        FuzzPosition,
        this,
        "getSqrtRatioAtTick",
        params,
        getContractByCodeHash
      );
    },
    getTickAtSqrtRatio: async (
      params: FuzzPositionTypes.CallMethodParams<"getTickAtSqrtRatio">
    ): Promise<FuzzPositionTypes.CallMethodResult<"getTickAtSqrtRatio">> => {
      return callMethod(
        FuzzPosition,
        this,
        "getTickAtSqrtRatio",
        params,
        getContractByCodeHash
      );
    },
    positionPath: async (
      params: FuzzPositionTypes.CallMethodParams<"positionPath">
    ): Promise<FuzzPositionTypes.CallMethodResult<"positionPath">> => {
      return callMethod(
        FuzzPosition,
        this,
        "positionPath",
        params,
        getContractByCodeHash
      );
    },
    positionContractId: async (
      params: FuzzPositionTypes.CallMethodParams<"positionContractId">
    ): Promise<FuzzPositionTypes.CallMethodResult<"positionContractId">> => {
      return callMethod(
        FuzzPosition,
        this,
        "positionContractId",
        params,
        getContractByCodeHash
      );
    },
    step: async (
      params: FuzzPositionTypes.CallMethodParams<"step">
    ): Promise<FuzzPositionTypes.CallMethodResult<"step">> => {
      return callMethod(
        FuzzPosition,
        this,
        "step",
        params,
        getContractByCodeHash
      );
    },
    deposit: async (
      params: FuzzPositionTypes.CallMethodParams<"deposit">
    ): Promise<FuzzPositionTypes.CallMethodResult<"deposit">> => {
      return callMethod(
        FuzzPosition,
        this,
        "deposit",
        params,
        getContractByCodeHash
      );
    },
    burnAndCollect: async (
      params: FuzzPositionTypes.CallMethodParams<"burnAndCollect">
    ): Promise<FuzzPositionTypes.CallMethodResult<"burnAndCollect">> => {
      return callMethod(
        FuzzPosition,
        this,
        "burnAndCollect",
        params,
        getContractByCodeHash
      );
    },
  };

  transact = {
    getSqrtRatioAtTick: async (
      params: FuzzPositionTypes.SignExecuteMethodParams<"getSqrtRatioAtTick">
    ): Promise<
      FuzzPositionTypes.SignExecuteMethodResult<"getSqrtRatioAtTick">
    > => {
      return signExecuteMethod(
        FuzzPosition,
        this,
        "getSqrtRatioAtTick",
        params
      );
    },
    getTickAtSqrtRatio: async (
      params: FuzzPositionTypes.SignExecuteMethodParams<"getTickAtSqrtRatio">
    ): Promise<
      FuzzPositionTypes.SignExecuteMethodResult<"getTickAtSqrtRatio">
    > => {
      return signExecuteMethod(
        FuzzPosition,
        this,
        "getTickAtSqrtRatio",
        params
      );
    },
    positionPath: async (
      params: FuzzPositionTypes.SignExecuteMethodParams<"positionPath">
    ): Promise<FuzzPositionTypes.SignExecuteMethodResult<"positionPath">> => {
      return signExecuteMethod(FuzzPosition, this, "positionPath", params);
    },
    positionContractId: async (
      params: FuzzPositionTypes.SignExecuteMethodParams<"positionContractId">
    ): Promise<
      FuzzPositionTypes.SignExecuteMethodResult<"positionContractId">
    > => {
      return signExecuteMethod(
        FuzzPosition,
        this,
        "positionContractId",
        params
      );
    },
    step: async (
      params: FuzzPositionTypes.SignExecuteMethodParams<"step">
    ): Promise<FuzzPositionTypes.SignExecuteMethodResult<"step">> => {
      return signExecuteMethod(FuzzPosition, this, "step", params);
    },
    deposit: async (
      params: FuzzPositionTypes.SignExecuteMethodParams<"deposit">
    ): Promise<FuzzPositionTypes.SignExecuteMethodResult<"deposit">> => {
      return signExecuteMethod(FuzzPosition, this, "deposit", params);
    },
    burnAndCollect: async (
      params: FuzzPositionTypes.SignExecuteMethodParams<"burnAndCollect">
    ): Promise<FuzzPositionTypes.SignExecuteMethodResult<"burnAndCollect">> => {
      return signExecuteMethod(FuzzPosition, this, "burnAndCollect", params);
    },
  };

  async multicall<Calls extends FuzzPositionTypes.MultiCallParams>(
    calls: Calls
  ): Promise<FuzzPositionTypes.MultiCallResults<Calls>>;
  async multicall<Callss extends FuzzPositionTypes.MultiCallParams[]>(
    callss: Narrow<Callss>
  ): Promise<FuzzPositionTypes.MulticallReturnType<Callss>>;
  async multicall<
    Callss extends
      | FuzzPositionTypes.MultiCallParams
      | FuzzPositionTypes.MultiCallParams[]
  >(callss: Callss): Promise<unknown> {
    return await multicallMethods(
      FuzzPosition,
      this,
      callss,
      getContractByCodeHash
    );
  }
}
