/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  Address,
  Contract,
  ContractState,
  TestContractResult,
  HexString,
  ContractFactory,
  EventSubscribeOptions,
  EventSubscription,
  CallContractParams,
  CallContractResult,
  TestContractParams,
  ContractEvent,
  subscribeContractEvent,
  subscribeContractEvents,
  testMethod,
  callMethod,
  multicallMethods,
  fetchContractState,
  Asset,
  ContractInstance,
  getContractEventsCurrentCount,
  TestContractParamsWithoutMaps,
  TestContractResultWithoutMaps,
  SignExecuteContractMethodParams,
  SignExecuteScriptTxResult,
  signExecuteMethod,
  addStdIdToFields,
  encodeContractFields,
  Narrow,
} from "@alephium/web3";
import { default as Pool0ContractJson } from "../Pool0.ral.json";
import { getContractByCodeHash, registerContract } from "./contracts";
import * as types from "./types";

// Custom types for the contract
export namespace Pool0Types {
  export type Fields = {
    bridge: HexString;
    ticks: HexString;
    tick: types.TickData0;
    price: bigint;
    refs: [bigint, bigint];
    spacing: bigint;
    positionTemplate: HexString;
    token2: HexString;
    currentPeriod: bigint;
    lastUpdate: bigint;
    rewards: [bigint, bigint, bigint];
    pendingRewards: [bigint, bigint, bigint];
    tickTemplate: HexString;
  };

  export type State = ContractState<Fields>;

  export interface CallMethodTable {
    delta0: {
      params: CallContractParams<{ p0: bigint; p1: bigint; liq: bigint }>;
      result: CallContractResult<bigint>;
    };
    delta1: {
      params: CallContractParams<{ p0: bigint; p1: bigint; liq: bigint }>;
      result: CallContractResult<bigint>;
    };
    positionPath: {
      params: CallContractParams<{ x: HexString; p: types.ModifyPosition }>;
      result: CallContractResult<HexString>;
    };
    addLiquidity: {
      params: CallContractParams<{ p0: bigint; p1: bigint; liq: bigint }>;
      result: CallContractResult<[bigint, bigint]>;
    };
    addTick: {
      params: CallContractParams<{
        caller: Address;
        index: bigint;
        delta: bigint;
        ref: bigint;
      }>;
      result: CallContractResult<types.TickData0>;
    };
    subTicks: {
      params: CallContractParams<{ mt: types.TickData0; t: types.TickData0 }>;
      result: CallContractResult<types.TickData0>;
    };
    modifyPosition: {
      params: CallContractParams<{
        time: bigint;
        id: HexString;
        p: types.ModifyPosition;
      }>;
      result: CallContractResult<null>;
    };
    swap: {
      params: CallContractParams<{
        time: bigint;
        id: HexString;
        p: types.Swap;
        priceLimit: bigint;
      }>;
      result: CallContractResult<null>;
    };
    distributeRewards: {
      params: CallContractParams<{ time: bigint }>;
      result: CallContractResult<null>;
    };
    donate: {
      params: CallContractParams<{
        time: bigint;
        id: HexString;
        p: types.Donate;
      }>;
      result: CallContractResult<null>;
    };
  }
  export type CallMethodParams<T extends keyof CallMethodTable> =
    CallMethodTable[T]["params"];
  export type CallMethodResult<T extends keyof CallMethodTable> =
    CallMethodTable[T]["result"];
  export type MultiCallParams = Partial<{
    [Name in keyof CallMethodTable]: CallMethodTable[Name]["params"];
  }>;
  export type MultiCallResults<T extends MultiCallParams> = {
    [MaybeName in keyof T]: MaybeName extends keyof CallMethodTable
      ? CallMethodTable[MaybeName]["result"]
      : undefined;
  };
  export type MulticallReturnType<Callss extends MultiCallParams[]> = {
    [index in keyof Callss]: MultiCallResults<Callss[index]>;
  };

  export interface SignExecuteMethodTable {
    delta0: {
      params: SignExecuteContractMethodParams<{
        p0: bigint;
        p1: bigint;
        liq: bigint;
      }>;
      result: SignExecuteScriptTxResult;
    };
    delta1: {
      params: SignExecuteContractMethodParams<{
        p0: bigint;
        p1: bigint;
        liq: bigint;
      }>;
      result: SignExecuteScriptTxResult;
    };
    positionPath: {
      params: SignExecuteContractMethodParams<{
        x: HexString;
        p: types.ModifyPosition;
      }>;
      result: SignExecuteScriptTxResult;
    };
    addLiquidity: {
      params: SignExecuteContractMethodParams<{
        p0: bigint;
        p1: bigint;
        liq: bigint;
      }>;
      result: SignExecuteScriptTxResult;
    };
    addTick: {
      params: SignExecuteContractMethodParams<{
        caller: Address;
        index: bigint;
        delta: bigint;
        ref: bigint;
      }>;
      result: SignExecuteScriptTxResult;
    };
    subTicks: {
      params: SignExecuteContractMethodParams<{
        mt: types.TickData0;
        t: types.TickData0;
      }>;
      result: SignExecuteScriptTxResult;
    };
    modifyPosition: {
      params: SignExecuteContractMethodParams<{
        time: bigint;
        id: HexString;
        p: types.ModifyPosition;
      }>;
      result: SignExecuteScriptTxResult;
    };
    swap: {
      params: SignExecuteContractMethodParams<{
        time: bigint;
        id: HexString;
        p: types.Swap;
        priceLimit: bigint;
      }>;
      result: SignExecuteScriptTxResult;
    };
    distributeRewards: {
      params: SignExecuteContractMethodParams<{ time: bigint }>;
      result: SignExecuteScriptTxResult;
    };
    donate: {
      params: SignExecuteContractMethodParams<{
        time: bigint;
        id: HexString;
        p: types.Donate;
      }>;
      result: SignExecuteScriptTxResult;
    };
  }
  export type SignExecuteMethodParams<T extends keyof SignExecuteMethodTable> =
    SignExecuteMethodTable[T]["params"];
  export type SignExecuteMethodResult<T extends keyof SignExecuteMethodTable> =
    SignExecuteMethodTable[T]["result"];
}

class Factory extends ContractFactory<Pool0Instance, Pool0Types.Fields> {
  encodeFields(fields: Pool0Types.Fields) {
    return encodeContractFields(
      addStdIdToFields(this.contract, fields),
      this.contract.fieldsSig,
      types.AllStructs
    );
  }

  consts = { I96: BigInt("79228162514264337593543950336") };

  at(address: string): Pool0Instance {
    return new Pool0Instance(address);
  }

  tests = {
    delta0: async (
      params: TestContractParamsWithoutMaps<
        Pool0Types.Fields,
        { p0: bigint; p1: bigint; liq: bigint }
      >
    ): Promise<TestContractResultWithoutMaps<bigint>> => {
      return testMethod(this, "delta0", params, getContractByCodeHash);
    },
    delta1: async (
      params: TestContractParamsWithoutMaps<
        Pool0Types.Fields,
        { p0: bigint; p1: bigint; liq: bigint }
      >
    ): Promise<TestContractResultWithoutMaps<bigint>> => {
      return testMethod(this, "delta1", params, getContractByCodeHash);
    },
    positionPath: async (
      params: TestContractParamsWithoutMaps<
        Pool0Types.Fields,
        { x: HexString; p: types.ModifyPosition }
      >
    ): Promise<TestContractResultWithoutMaps<HexString>> => {
      return testMethod(this, "positionPath", params, getContractByCodeHash);
    },
    addLiquidity: async (
      params: TestContractParamsWithoutMaps<
        Pool0Types.Fields,
        { p0: bigint; p1: bigint; liq: bigint }
      >
    ): Promise<TestContractResultWithoutMaps<[bigint, bigint]>> => {
      return testMethod(this, "addLiquidity", params, getContractByCodeHash);
    },
    addTick: async (
      params: TestContractParamsWithoutMaps<
        Pool0Types.Fields,
        { caller: Address; index: bigint; delta: bigint; ref: bigint }
      >
    ): Promise<TestContractResultWithoutMaps<types.TickData0>> => {
      return testMethod(this, "addTick", params, getContractByCodeHash);
    },
    subTicks: async (
      params: TestContractParamsWithoutMaps<
        Pool0Types.Fields,
        { mt: types.TickData0; t: types.TickData0 }
      >
    ): Promise<TestContractResultWithoutMaps<types.TickData0>> => {
      return testMethod(this, "subTicks", params, getContractByCodeHash);
    },
    modifyPosition: async (
      params: TestContractParamsWithoutMaps<
        Pool0Types.Fields,
        { time: bigint; id: HexString; p: types.ModifyPosition }
      >
    ): Promise<TestContractResultWithoutMaps<null>> => {
      return testMethod(this, "modifyPosition", params, getContractByCodeHash);
    },
    swap: async (
      params: TestContractParamsWithoutMaps<
        Pool0Types.Fields,
        { time: bigint; id: HexString; p: types.Swap; priceLimit: bigint }
      >
    ): Promise<TestContractResultWithoutMaps<null>> => {
      return testMethod(this, "swap", params, getContractByCodeHash);
    },
    distributeRewards: async (
      params: TestContractParamsWithoutMaps<Pool0Types.Fields, { time: bigint }>
    ): Promise<TestContractResultWithoutMaps<null>> => {
      return testMethod(
        this,
        "distributeRewards",
        params,
        getContractByCodeHash
      );
    },
    donate: async (
      params: TestContractParamsWithoutMaps<
        Pool0Types.Fields,
        { time: bigint; id: HexString; p: types.Donate }
      >
    ): Promise<TestContractResultWithoutMaps<null>> => {
      return testMethod(this, "donate", params, getContractByCodeHash);
    },
  };

  stateForTest(initFields: Pool0Types.Fields, asset?: Asset, address?: string) {
    return this.stateForTest_(initFields, asset, address, undefined);
  }
}

// Use this object to test and deploy the contract
export const Pool0 = new Factory(
  Contract.fromJson(
    Pool0ContractJson,
    "",
    "1eb3e8f9da163fca695c5a532d16b3c0a8e4ee781f4a7e7fdd2a38270180645c",
    types.AllStructs
  )
);
registerContract(Pool0);

// Use this class to interact with the blockchain
export class Pool0Instance extends ContractInstance {
  constructor(address: Address) {
    super(address);
  }

  async fetchState(): Promise<Pool0Types.State> {
    return fetchContractState(Pool0, this);
  }

  view = {
    delta0: async (
      params: Pool0Types.CallMethodParams<"delta0">
    ): Promise<Pool0Types.CallMethodResult<"delta0">> => {
      return callMethod(Pool0, this, "delta0", params, getContractByCodeHash);
    },
    delta1: async (
      params: Pool0Types.CallMethodParams<"delta1">
    ): Promise<Pool0Types.CallMethodResult<"delta1">> => {
      return callMethod(Pool0, this, "delta1", params, getContractByCodeHash);
    },
    positionPath: async (
      params: Pool0Types.CallMethodParams<"positionPath">
    ): Promise<Pool0Types.CallMethodResult<"positionPath">> => {
      return callMethod(
        Pool0,
        this,
        "positionPath",
        params,
        getContractByCodeHash
      );
    },
    addLiquidity: async (
      params: Pool0Types.CallMethodParams<"addLiquidity">
    ): Promise<Pool0Types.CallMethodResult<"addLiquidity">> => {
      return callMethod(
        Pool0,
        this,
        "addLiquidity",
        params,
        getContractByCodeHash
      );
    },
    addTick: async (
      params: Pool0Types.CallMethodParams<"addTick">
    ): Promise<Pool0Types.CallMethodResult<"addTick">> => {
      return callMethod(Pool0, this, "addTick", params, getContractByCodeHash);
    },
    subTicks: async (
      params: Pool0Types.CallMethodParams<"subTicks">
    ): Promise<Pool0Types.CallMethodResult<"subTicks">> => {
      return callMethod(Pool0, this, "subTicks", params, getContractByCodeHash);
    },
    modifyPosition: async (
      params: Pool0Types.CallMethodParams<"modifyPosition">
    ): Promise<Pool0Types.CallMethodResult<"modifyPosition">> => {
      return callMethod(
        Pool0,
        this,
        "modifyPosition",
        params,
        getContractByCodeHash
      );
    },
    swap: async (
      params: Pool0Types.CallMethodParams<"swap">
    ): Promise<Pool0Types.CallMethodResult<"swap">> => {
      return callMethod(Pool0, this, "swap", params, getContractByCodeHash);
    },
    distributeRewards: async (
      params: Pool0Types.CallMethodParams<"distributeRewards">
    ): Promise<Pool0Types.CallMethodResult<"distributeRewards">> => {
      return callMethod(
        Pool0,
        this,
        "distributeRewards",
        params,
        getContractByCodeHash
      );
    },
    donate: async (
      params: Pool0Types.CallMethodParams<"donate">
    ): Promise<Pool0Types.CallMethodResult<"donate">> => {
      return callMethod(Pool0, this, "donate", params, getContractByCodeHash);
    },
  };

  transact = {
    delta0: async (
      params: Pool0Types.SignExecuteMethodParams<"delta0">
    ): Promise<Pool0Types.SignExecuteMethodResult<"delta0">> => {
      return signExecuteMethod(Pool0, this, "delta0", params);
    },
    delta1: async (
      params: Pool0Types.SignExecuteMethodParams<"delta1">
    ): Promise<Pool0Types.SignExecuteMethodResult<"delta1">> => {
      return signExecuteMethod(Pool0, this, "delta1", params);
    },
    positionPath: async (
      params: Pool0Types.SignExecuteMethodParams<"positionPath">
    ): Promise<Pool0Types.SignExecuteMethodResult<"positionPath">> => {
      return signExecuteMethod(Pool0, this, "positionPath", params);
    },
    addLiquidity: async (
      params: Pool0Types.SignExecuteMethodParams<"addLiquidity">
    ): Promise<Pool0Types.SignExecuteMethodResult<"addLiquidity">> => {
      return signExecuteMethod(Pool0, this, "addLiquidity", params);
    },
    addTick: async (
      params: Pool0Types.SignExecuteMethodParams<"addTick">
    ): Promise<Pool0Types.SignExecuteMethodResult<"addTick">> => {
      return signExecuteMethod(Pool0, this, "addTick", params);
    },
    subTicks: async (
      params: Pool0Types.SignExecuteMethodParams<"subTicks">
    ): Promise<Pool0Types.SignExecuteMethodResult<"subTicks">> => {
      return signExecuteMethod(Pool0, this, "subTicks", params);
    },
    modifyPosition: async (
      params: Pool0Types.SignExecuteMethodParams<"modifyPosition">
    ): Promise<Pool0Types.SignExecuteMethodResult<"modifyPosition">> => {
      return signExecuteMethod(Pool0, this, "modifyPosition", params);
    },
    swap: async (
      params: Pool0Types.SignExecuteMethodParams<"swap">
    ): Promise<Pool0Types.SignExecuteMethodResult<"swap">> => {
      return signExecuteMethod(Pool0, this, "swap", params);
    },
    distributeRewards: async (
      params: Pool0Types.SignExecuteMethodParams<"distributeRewards">
    ): Promise<Pool0Types.SignExecuteMethodResult<"distributeRewards">> => {
      return signExecuteMethod(Pool0, this, "distributeRewards", params);
    },
    donate: async (
      params: Pool0Types.SignExecuteMethodParams<"donate">
    ): Promise<Pool0Types.SignExecuteMethodResult<"donate">> => {
      return signExecuteMethod(Pool0, this, "donate", params);
    },
  };

  async multicall<Calls extends Pool0Types.MultiCallParams>(
    calls: Calls
  ): Promise<Pool0Types.MultiCallResults<Calls>>;
  async multicall<Callss extends Pool0Types.MultiCallParams[]>(
    callss: Narrow<Callss>
  ): Promise<Pool0Types.MulticallReturnType<Callss>>;
  async multicall<
    Callss extends Pool0Types.MultiCallParams | Pool0Types.MultiCallParams[]
  >(callss: Callss): Promise<unknown> {
    return await multicallMethods(Pool0, this, callss, getContractByCodeHash);
  }
}
