/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  Address,
  Contract,
  ContractState,
  TestContractResult,
  HexString,
  ContractFactory,
  EventSubscribeOptions,
  EventSubscription,
  CallContractParams,
  CallContractResult,
  TestContractParams,
  ContractEvent,
  subscribeContractEvent,
  subscribeContractEvents,
  testMethod,
  callMethod,
  multicallMethods,
  fetchContractState,
  Asset,
  ContractInstance,
  getContractEventsCurrentCount,
  TestContractParamsWithoutMaps,
  TestContractResultWithoutMaps,
  SignExecuteContractMethodParams,
  SignExecuteScriptTxResult,
  signExecuteMethod,
  addStdIdToFields,
  encodeContractFields,
  Narrow,
} from "@alephium/web3";
import { default as Position0ContractJson } from "../Position0.ral.json";
import { getContractByCodeHash, registerContract } from "./contracts";
import * as types from "./types";

// Custom types for the contract
export namespace Position0Types {
  export type Fields = {
    pool: HexString;
    tick: types.TickData0;
  };

  export type State = ContractState<Fields>;

  export interface CallMethodTable {
    update: {
      params: CallContractParams<{
        account: Address;
        t: types.TickData0;
        token0: HexString;
        amount0: bigint;
        token1: HexString;
        amount1: bigint;
        token2: HexString;
      }>;
      result: CallContractResult<null>;
    };
  }
  export type CallMethodParams<T extends keyof CallMethodTable> =
    CallMethodTable[T]["params"];
  export type CallMethodResult<T extends keyof CallMethodTable> =
    CallMethodTable[T]["result"];
  export type MultiCallParams = Partial<{
    [Name in keyof CallMethodTable]: CallMethodTable[Name]["params"];
  }>;
  export type MultiCallResults<T extends MultiCallParams> = {
    [MaybeName in keyof T]: MaybeName extends keyof CallMethodTable
      ? CallMethodTable[MaybeName]["result"]
      : undefined;
  };
  export type MulticallReturnType<Callss extends MultiCallParams[]> = {
    [index in keyof Callss]: MultiCallResults<Callss[index]>;
  };

  export interface SignExecuteMethodTable {
    update: {
      params: SignExecuteContractMethodParams<{
        account: Address;
        t: types.TickData0;
        token0: HexString;
        amount0: bigint;
        token1: HexString;
        amount1: bigint;
        token2: HexString;
      }>;
      result: SignExecuteScriptTxResult;
    };
  }
  export type SignExecuteMethodParams<T extends keyof SignExecuteMethodTable> =
    SignExecuteMethodTable[T]["params"];
  export type SignExecuteMethodResult<T extends keyof SignExecuteMethodTable> =
    SignExecuteMethodTable[T]["result"];
}

class Factory extends ContractFactory<
  Position0Instance,
  Position0Types.Fields
> {
  encodeFields(fields: Position0Types.Fields) {
    return encodeContractFields(
      addStdIdToFields(this.contract, fields),
      this.contract.fieldsSig,
      types.AllStructs
    );
  }

  at(address: string): Position0Instance {
    return new Position0Instance(address);
  }

  tests = {
    update: async (
      params: TestContractParamsWithoutMaps<
        Position0Types.Fields,
        {
          account: Address;
          t: types.TickData0;
          token0: HexString;
          amount0: bigint;
          token1: HexString;
          amount1: bigint;
          token2: HexString;
        }
      >
    ): Promise<TestContractResultWithoutMaps<null>> => {
      return testMethod(this, "update", params, getContractByCodeHash);
    },
  };

  stateForTest(
    initFields: Position0Types.Fields,
    asset?: Asset,
    address?: string
  ) {
    return this.stateForTest_(initFields, asset, address, undefined);
  }
}

// Use this object to test and deploy the contract
export const Position0 = new Factory(
  Contract.fromJson(
    Position0ContractJson,
    "",
    "7d71857b68e04086dd914aacd08cecd7de20b1698be775c40e95176b14084f0b",
    types.AllStructs
  )
);
registerContract(Position0);

// Use this class to interact with the blockchain
export class Position0Instance extends ContractInstance {
  constructor(address: Address) {
    super(address);
  }

  async fetchState(): Promise<Position0Types.State> {
    return fetchContractState(Position0, this);
  }

  view = {
    update: async (
      params: Position0Types.CallMethodParams<"update">
    ): Promise<Position0Types.CallMethodResult<"update">> => {
      return callMethod(
        Position0,
        this,
        "update",
        params,
        getContractByCodeHash
      );
    },
  };

  transact = {
    update: async (
      params: Position0Types.SignExecuteMethodParams<"update">
    ): Promise<Position0Types.SignExecuteMethodResult<"update">> => {
      return signExecuteMethod(Position0, this, "update", params);
    },
  };
}
