/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  Address,
  ExecutableScript,
  ExecuteScriptParams,
  ExecuteScriptResult,
  Script,
  SignerProvider,
  HexString,
} from "@alephium/web3";
import { getContractByCodeHash } from "./contracts";
import { default as FlashTestScriptJson } from "../FlashTest.ral.json";
import { default as PoolRouterDemoScriptJson } from "../PoolRouterDemo.ral.json";
import * as types from "./types";

export const FlashTest = new ExecutableScript<{
  t: HexString;
  data: HexString;
}>(
  Script.fromJson(FlashTestScriptJson, "", types.AllStructs),
  getContractByCodeHash
);

export const PoolRouterDemo = new ExecutableScript<{
  pool_: HexString;
  position_: HexString;
  tick_: HexString;
  word_: HexString;
  factory_: HexString;
  user_: HexString;
  config_: HexString;
  counter: bigint;
}>(
  Script.fromJson(PoolRouterDemoScriptJson, "", types.AllStructs),
  getContractByCodeHash
);
