/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  Address,
  Contract,
  ContractState,
  TestContractResult,
  HexString,
  ContractFactory,
  EventSubscribeOptions,
  EventSubscription,
  CallContractParams,
  CallContractResult,
  TestContractParams,
  ContractEvent,
  subscribeContractEvent,
  subscribeContractEvents,
  testMethod,
  callMethod,
  multicallMethods,
  fetchContractState,
  Asset,
  ContractInstance,
  getContractEventsCurrentCount,
  TestContractParamsWithoutMaps,
  TestContractResultWithoutMaps,
  SignExecuteContractMethodParams,
  SignExecuteScriptTxResult,
  signExecuteMethod,
  addStdIdToFields,
  encodeContractFields,
  Narrow,
} from "@alephium/web3";
import { default as TestDexAccountPoolContractJson } from "../test/TestDexAccountPool.ral.json";
import { getContractByCodeHash, registerContract } from "./contracts";
import * as types from "./types";

// Custom types for the contract
export namespace TestDexAccountPoolTypes {
  export type Fields = {
    path: HexString;
  };

  export type State = ContractState<Fields>;

  export interface CallMethodTable {
    callDeposit: {
      params: CallContractParams<{
        acc: HexString;
        payer: Address;
        tokenId: HexString;
        amount: bigint;
      }>;
      result: CallContractResult<null>;
    };
  }
  export type CallMethodParams<T extends keyof CallMethodTable> =
    CallMethodTable[T]["params"];
  export type CallMethodResult<T extends keyof CallMethodTable> =
    CallMethodTable[T]["result"];
  export type MultiCallParams = Partial<{
    [Name in keyof CallMethodTable]: CallMethodTable[Name]["params"];
  }>;
  export type MultiCallResults<T extends MultiCallParams> = {
    [MaybeName in keyof T]: MaybeName extends keyof CallMethodTable
      ? CallMethodTable[MaybeName]["result"]
      : undefined;
  };
  export type MulticallReturnType<Callss extends MultiCallParams[]> = {
    [index in keyof Callss]: MultiCallResults<Callss[index]>;
  };

  export interface SignExecuteMethodTable {
    callDeposit: {
      params: SignExecuteContractMethodParams<{
        acc: HexString;
        payer: Address;
        tokenId: HexString;
        amount: bigint;
      }>;
      result: SignExecuteScriptTxResult;
    };
  }
  export type SignExecuteMethodParams<T extends keyof SignExecuteMethodTable> =
    SignExecuteMethodTable[T]["params"];
  export type SignExecuteMethodResult<T extends keyof SignExecuteMethodTable> =
    SignExecuteMethodTable[T]["result"];
}

class Factory extends ContractFactory<
  TestDexAccountPoolInstance,
  TestDexAccountPoolTypes.Fields
> {
  encodeFields(fields: TestDexAccountPoolTypes.Fields) {
    return encodeContractFields(
      addStdIdToFields(this.contract, fields),
      this.contract.fieldsSig,
      types.AllStructs
    );
  }

  at(address: string): TestDexAccountPoolInstance {
    return new TestDexAccountPoolInstance(address);
  }

  tests = {
    callDeposit: async (
      params: TestContractParamsWithoutMaps<
        TestDexAccountPoolTypes.Fields,
        { acc: HexString; payer: Address; tokenId: HexString; amount: bigint }
      >
    ): Promise<TestContractResultWithoutMaps<null>> => {
      return testMethod(this, "callDeposit", params, getContractByCodeHash);
    },
  };

  stateForTest(
    initFields: TestDexAccountPoolTypes.Fields,
    asset?: Asset,
    address?: string
  ) {
    return this.stateForTest_(initFields, asset, address, undefined);
  }
}

// Use this object to test and deploy the contract
export const TestDexAccountPool = new Factory(
  Contract.fromJson(
    TestDexAccountPoolContractJson,
    "",
    "3f1fb343334b79f9883f8a82dfc4e3bed7bc4349c9dec876ec7b85b970c2e6f5",
    types.AllStructs
  )
);
registerContract(TestDexAccountPool);

// Use this class to interact with the blockchain
export class TestDexAccountPoolInstance extends ContractInstance {
  constructor(address: Address) {
    super(address);
  }

  async fetchState(): Promise<TestDexAccountPoolTypes.State> {
    return fetchContractState(TestDexAccountPool, this);
  }

  view = {
    callDeposit: async (
      params: TestDexAccountPoolTypes.CallMethodParams<"callDeposit">
    ): Promise<TestDexAccountPoolTypes.CallMethodResult<"callDeposit">> => {
      return callMethod(
        TestDexAccountPool,
        this,
        "callDeposit",
        params,
        getContractByCodeHash
      );
    },
  };

  transact = {
    callDeposit: async (
      params: TestDexAccountPoolTypes.SignExecuteMethodParams<"callDeposit">
    ): Promise<
      TestDexAccountPoolTypes.SignExecuteMethodResult<"callDeposit">
    > => {
      return signExecuteMethod(TestDexAccountPool, this, "callDeposit", params);
    },
  };
}
