/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  Address,
  Contract,
  ContractState,
  TestContractResult,
  HexString,
  ContractFactory,
  EventSubscribeOptions,
  EventSubscription,
  CallContractParams,
  CallContractResult,
  TestContractParams,
  ContractEvent,
  subscribeContractEvent,
  subscribeContractEvents,
  testMethod,
  callMethod,
  multicallMethods,
  fetchContractState,
  Asset,
  ContractInstance,
  getContractEventsCurrentCount,
  TestContractParamsWithoutMaps,
  TestContractResultWithoutMaps,
  SignExecuteContractMethodParams,
  SignExecuteScriptTxResult,
  signExecuteMethod,
  addStdIdToFields,
  encodeContractFields,
  Narrow,
} from "@alephium/web3";
import { default as TestDexAccountDeployerContractJson } from "../test/TestDexAccountDeployer.ral.json";
import { getContractByCodeHash, registerContract } from "./contracts";
import * as types from "./types";

// Custom types for the contract
export namespace TestDexAccountDeployerTypes {
  export type State = Omit<ContractState<any>, "fields">;

  export interface CallMethodTable {
    deployPool: {
      params: CallContractParams<{ path: HexString; template: HexString }>;
      result: CallContractResult<HexString>;
    };
    deployAcc: {
      params: CallContractParams<{
        root: Address;
        parents: [HexString, HexString];
        payer: Address;
        ref: Address;
        template: HexString;
      }>;
      result: CallContractResult<HexString>;
    };
  }
  export type CallMethodParams<T extends keyof CallMethodTable> =
    CallMethodTable[T]["params"];
  export type CallMethodResult<T extends keyof CallMethodTable> =
    CallMethodTable[T]["result"];
  export type MultiCallParams = Partial<{
    [Name in keyof CallMethodTable]: CallMethodTable[Name]["params"];
  }>;
  export type MultiCallResults<T extends MultiCallParams> = {
    [MaybeName in keyof T]: MaybeName extends keyof CallMethodTable
      ? CallMethodTable[MaybeName]["result"]
      : undefined;
  };
  export type MulticallReturnType<Callss extends MultiCallParams[]> = {
    [index in keyof Callss]: MultiCallResults<Callss[index]>;
  };

  export interface SignExecuteMethodTable {
    deployPool: {
      params: SignExecuteContractMethodParams<{
        path: HexString;
        template: HexString;
      }>;
      result: SignExecuteScriptTxResult;
    };
    deployAcc: {
      params: SignExecuteContractMethodParams<{
        root: Address;
        parents: [HexString, HexString];
        payer: Address;
        ref: Address;
        template: HexString;
      }>;
      result: SignExecuteScriptTxResult;
    };
  }
  export type SignExecuteMethodParams<T extends keyof SignExecuteMethodTable> =
    SignExecuteMethodTable[T]["params"];
  export type SignExecuteMethodResult<T extends keyof SignExecuteMethodTable> =
    SignExecuteMethodTable[T]["result"];
}

class Factory extends ContractFactory<TestDexAccountDeployerInstance, {}> {
  encodeFields() {
    return encodeContractFields({}, this.contract.fieldsSig, types.AllStructs);
  }

  at(address: string): TestDexAccountDeployerInstance {
    return new TestDexAccountDeployerInstance(address);
  }

  tests = {
    deployPool: async (
      params: Omit<
        TestContractParamsWithoutMaps<
          never,
          { path: HexString; template: HexString }
        >,
        "initialFields"
      >
    ): Promise<TestContractResultWithoutMaps<HexString>> => {
      return testMethod(this, "deployPool", params, getContractByCodeHash);
    },
    deployAcc: async (
      params: Omit<
        TestContractParamsWithoutMaps<
          never,
          {
            root: Address;
            parents: [HexString, HexString];
            payer: Address;
            ref: Address;
            template: HexString;
          }
        >,
        "initialFields"
      >
    ): Promise<TestContractResultWithoutMaps<HexString>> => {
      return testMethod(this, "deployAcc", params, getContractByCodeHash);
    },
  };

  stateForTest(initFields: {}, asset?: Asset, address?: string) {
    return this.stateForTest_(initFields, asset, address, undefined);
  }
}

// Use this object to test and deploy the contract
export const TestDexAccountDeployer = new Factory(
  Contract.fromJson(
    TestDexAccountDeployerContractJson,
    "",
    "0cbb1fe07db02de9bc2ea89533880d498de4050fd667f175de61d8796e7ca1f4",
    types.AllStructs
  )
);
registerContract(TestDexAccountDeployer);

// Use this class to interact with the blockchain
export class TestDexAccountDeployerInstance extends ContractInstance {
  constructor(address: Address) {
    super(address);
  }

  async fetchState(): Promise<TestDexAccountDeployerTypes.State> {
    return fetchContractState(TestDexAccountDeployer, this);
  }

  view = {
    deployPool: async (
      params: TestDexAccountDeployerTypes.CallMethodParams<"deployPool">
    ): Promise<TestDexAccountDeployerTypes.CallMethodResult<"deployPool">> => {
      return callMethod(
        TestDexAccountDeployer,
        this,
        "deployPool",
        params,
        getContractByCodeHash
      );
    },
    deployAcc: async (
      params: TestDexAccountDeployerTypes.CallMethodParams<"deployAcc">
    ): Promise<TestDexAccountDeployerTypes.CallMethodResult<"deployAcc">> => {
      return callMethod(
        TestDexAccountDeployer,
        this,
        "deployAcc",
        params,
        getContractByCodeHash
      );
    },
  };

  transact = {
    deployPool: async (
      params: TestDexAccountDeployerTypes.SignExecuteMethodParams<"deployPool">
    ): Promise<
      TestDexAccountDeployerTypes.SignExecuteMethodResult<"deployPool">
    > => {
      return signExecuteMethod(
        TestDexAccountDeployer,
        this,
        "deployPool",
        params
      );
    },
    deployAcc: async (
      params: TestDexAccountDeployerTypes.SignExecuteMethodParams<"deployAcc">
    ): Promise<
      TestDexAccountDeployerTypes.SignExecuteMethodResult<"deployAcc">
    > => {
      return signExecuteMethod(
        TestDexAccountDeployer,
        this,
        "deployAcc",
        params
      );
    },
  };

  async multicall<Calls extends TestDexAccountDeployerTypes.MultiCallParams>(
    calls: Calls
  ): Promise<TestDexAccountDeployerTypes.MultiCallResults<Calls>>;
  async multicall<Callss extends TestDexAccountDeployerTypes.MultiCallParams[]>(
    callss: Narrow<Callss>
  ): Promise<TestDexAccountDeployerTypes.MulticallReturnType<Callss>>;
  async multicall<
    Callss extends
      | TestDexAccountDeployerTypes.MultiCallParams
      | TestDexAccountDeployerTypes.MultiCallParams[]
  >(callss: Callss): Promise<unknown> {
    return await multicallMethods(
      TestDexAccountDeployer,
      this,
      callss,
      getContractByCodeHash
    );
  }
}
