/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  Address,
  Contract,
  ContractState,
  TestContractResult,
  HexString,
  ContractFactory,
  EventSubscribeOptions,
  EventSubscription,
  CallContractParams,
  CallContractResult,
  TestContractParams,
  ContractEvent,
  subscribeContractEvent,
  subscribeContractEvents,
  testMethod,
  callMethod,
  multicallMethods,
  fetchContractState,
  Asset,
  ContractInstance,
  getContractEventsCurrentCount,
  TestContractParamsWithoutMaps,
  TestContractResultWithoutMaps,
  SignExecuteContractMethodParams,
  SignExecuteScriptTxResult,
  signExecuteMethod,
  addStdIdToFields,
  encodeContractFields,
  Narrow,
} from "@alephium/web3";
import { default as Ticks0ContractJson } from "../Ticks0.ral.json";
import { getContractByCodeHash, registerContract } from "./contracts";
import * as types from "./types";

// Custom types for the contract
export namespace Ticks0Types {
  export type Fields = {
    pool: HexString;
    lower: bigint;
    upper: bigint;
    ticks: [
      types.TickData0,
      types.TickData0,
      types.TickData0,
      types.TickData0,
      types.TickData0,
      types.TickData0,
      types.TickData0,
      types.TickData0,
      types.TickData0,
      types.TickData0,
      types.TickData0,
      types.TickData0,
      types.TickData0,
      types.TickData0,
      types.TickData0,
      types.TickData0,
      types.TickData0,
      types.TickData0,
      types.TickData0,
      types.TickData0,
      types.TickData0,
      types.TickData0,
      types.TickData0,
      types.TickData0,
      types.TickData0
    ];
  };

  export type State = ContractState<Fields>;

  export interface CallMethodTable {
    delta0: {
      params: CallContractParams<{ p0: bigint; p1: bigint; liq: bigint }>;
      result: CallContractResult<bigint>;
    };
    delta1: {
      params: CallContractParams<{ p0: bigint; p1: bigint; liq: bigint }>;
      result: CallContractResult<bigint>;
    };
    subTicks: {
      params: CallContractParams<{ tick: types.TickData0; t: types.TickData0 }>;
      result: CallContractResult<types.TickData0>;
    };
    update: {
      params: CallContractParams<{
        p: types.ModifyPosition;
        tick: types.TickData0;
        price: bigint;
      }>;
      result: CallContractResult<[bigint, bigint, [bigint, bigint, bigint]]>;
    };
    swap: {
      params: CallContractParams<{
        tick: types.TickData0;
        price: bigint;
        fee: bigint;
        zeroForOne: boolean;
        amount0: bigint;
        amount1: bigint;
        priceLimit: bigint;
      }>;
      result: CallContractResult<[types.TickData0, bigint, bigint, bigint]>;
    };
  }
  export type CallMethodParams<T extends keyof CallMethodTable> =
    CallMethodTable[T]["params"];
  export type CallMethodResult<T extends keyof CallMethodTable> =
    CallMethodTable[T]["result"];
  export type MultiCallParams = Partial<{
    [Name in keyof CallMethodTable]: CallMethodTable[Name]["params"];
  }>;
  export type MultiCallResults<T extends MultiCallParams> = {
    [MaybeName in keyof T]: MaybeName extends keyof CallMethodTable
      ? CallMethodTable[MaybeName]["result"]
      : undefined;
  };
  export type MulticallReturnType<Callss extends MultiCallParams[]> = {
    [index in keyof Callss]: MultiCallResults<Callss[index]>;
  };

  export interface SignExecuteMethodTable {
    delta0: {
      params: SignExecuteContractMethodParams<{
        p0: bigint;
        p1: bigint;
        liq: bigint;
      }>;
      result: SignExecuteScriptTxResult;
    };
    delta1: {
      params: SignExecuteContractMethodParams<{
        p0: bigint;
        p1: bigint;
        liq: bigint;
      }>;
      result: SignExecuteScriptTxResult;
    };
    subTicks: {
      params: SignExecuteContractMethodParams<{
        tick: types.TickData0;
        t: types.TickData0;
      }>;
      result: SignExecuteScriptTxResult;
    };
    update: {
      params: SignExecuteContractMethodParams<{
        p: types.ModifyPosition;
        tick: types.TickData0;
        price: bigint;
      }>;
      result: SignExecuteScriptTxResult;
    };
    swap: {
      params: SignExecuteContractMethodParams<{
        tick: types.TickData0;
        price: bigint;
        fee: bigint;
        zeroForOne: boolean;
        amount0: bigint;
        amount1: bigint;
        priceLimit: bigint;
      }>;
      result: SignExecuteScriptTxResult;
    };
  }
  export type SignExecuteMethodParams<T extends keyof SignExecuteMethodTable> =
    SignExecuteMethodTable[T]["params"];
  export type SignExecuteMethodResult<T extends keyof SignExecuteMethodTable> =
    SignExecuteMethodTable[T]["result"];
}

class Factory extends ContractFactory<Ticks0Instance, Ticks0Types.Fields> {
  encodeFields(fields: Ticks0Types.Fields) {
    return encodeContractFields(
      addStdIdToFields(this.contract, fields),
      this.contract.fieldsSig,
      types.AllStructs
    );
  }

  consts = { I96: BigInt("79228162514264337593543950336") };

  at(address: string): Ticks0Instance {
    return new Ticks0Instance(address);
  }

  tests = {
    delta0: async (
      params: TestContractParamsWithoutMaps<
        Ticks0Types.Fields,
        { p0: bigint; p1: bigint; liq: bigint }
      >
    ): Promise<TestContractResultWithoutMaps<bigint>> => {
      return testMethod(this, "delta0", params, getContractByCodeHash);
    },
    delta1: async (
      params: TestContractParamsWithoutMaps<
        Ticks0Types.Fields,
        { p0: bigint; p1: bigint; liq: bigint }
      >
    ): Promise<TestContractResultWithoutMaps<bigint>> => {
      return testMethod(this, "delta1", params, getContractByCodeHash);
    },
    subTicks: async (
      params: TestContractParamsWithoutMaps<
        Ticks0Types.Fields,
        { tick: types.TickData0; t: types.TickData0 }
      >
    ): Promise<TestContractResultWithoutMaps<types.TickData0>> => {
      return testMethod(this, "subTicks", params, getContractByCodeHash);
    },
    update: async (
      params: TestContractParamsWithoutMaps<
        Ticks0Types.Fields,
        { p: types.ModifyPosition; tick: types.TickData0; price: bigint }
      >
    ): Promise<
      TestContractResultWithoutMaps<[bigint, bigint, [bigint, bigint, bigint]]>
    > => {
      return testMethod(this, "update", params, getContractByCodeHash);
    },
    swap: async (
      params: TestContractParamsWithoutMaps<
        Ticks0Types.Fields,
        {
          tick: types.TickData0;
          price: bigint;
          fee: bigint;
          zeroForOne: boolean;
          amount0: bigint;
          amount1: bigint;
          priceLimit: bigint;
        }
      >
    ): Promise<
      TestContractResultWithoutMaps<[types.TickData0, bigint, bigint, bigint]>
    > => {
      return testMethod(this, "swap", params, getContractByCodeHash);
    },
  };

  stateForTest(
    initFields: Ticks0Types.Fields,
    asset?: Asset,
    address?: string
  ) {
    return this.stateForTest_(initFields, asset, address, undefined);
  }
}

// Use this object to test and deploy the contract
export const Ticks0 = new Factory(
  Contract.fromJson(
    Ticks0ContractJson,
    "",
    "a0866a813c178f52c0b28b5807b751719546f47fa17ee41fb3fa12df1d38e3ba",
    types.AllStructs
  )
);
registerContract(Ticks0);

// Use this class to interact with the blockchain
export class Ticks0Instance extends ContractInstance {
  constructor(address: Address) {
    super(address);
  }

  async fetchState(): Promise<Ticks0Types.State> {
    return fetchContractState(Ticks0, this);
  }

  view = {
    delta0: async (
      params: Ticks0Types.CallMethodParams<"delta0">
    ): Promise<Ticks0Types.CallMethodResult<"delta0">> => {
      return callMethod(Ticks0, this, "delta0", params, getContractByCodeHash);
    },
    delta1: async (
      params: Ticks0Types.CallMethodParams<"delta1">
    ): Promise<Ticks0Types.CallMethodResult<"delta1">> => {
      return callMethod(Ticks0, this, "delta1", params, getContractByCodeHash);
    },
    subTicks: async (
      params: Ticks0Types.CallMethodParams<"subTicks">
    ): Promise<Ticks0Types.CallMethodResult<"subTicks">> => {
      return callMethod(
        Ticks0,
        this,
        "subTicks",
        params,
        getContractByCodeHash
      );
    },
    update: async (
      params: Ticks0Types.CallMethodParams<"update">
    ): Promise<Ticks0Types.CallMethodResult<"update">> => {
      return callMethod(Ticks0, this, "update", params, getContractByCodeHash);
    },
    swap: async (
      params: Ticks0Types.CallMethodParams<"swap">
    ): Promise<Ticks0Types.CallMethodResult<"swap">> => {
      return callMethod(Ticks0, this, "swap", params, getContractByCodeHash);
    },
  };

  transact = {
    delta0: async (
      params: Ticks0Types.SignExecuteMethodParams<"delta0">
    ): Promise<Ticks0Types.SignExecuteMethodResult<"delta0">> => {
      return signExecuteMethod(Ticks0, this, "delta0", params);
    },
    delta1: async (
      params: Ticks0Types.SignExecuteMethodParams<"delta1">
    ): Promise<Ticks0Types.SignExecuteMethodResult<"delta1">> => {
      return signExecuteMethod(Ticks0, this, "delta1", params);
    },
    subTicks: async (
      params: Ticks0Types.SignExecuteMethodParams<"subTicks">
    ): Promise<Ticks0Types.SignExecuteMethodResult<"subTicks">> => {
      return signExecuteMethod(Ticks0, this, "subTicks", params);
    },
    update: async (
      params: Ticks0Types.SignExecuteMethodParams<"update">
    ): Promise<Ticks0Types.SignExecuteMethodResult<"update">> => {
      return signExecuteMethod(Ticks0, this, "update", params);
    },
    swap: async (
      params: Ticks0Types.SignExecuteMethodParams<"swap">
    ): Promise<Ticks0Types.SignExecuteMethodResult<"swap">> => {
      return signExecuteMethod(Ticks0, this, "swap", params);
    },
  };

  async multicall<Calls extends Ticks0Types.MultiCallParams>(
    calls: Calls
  ): Promise<Ticks0Types.MultiCallResults<Calls>>;
  async multicall<Callss extends Ticks0Types.MultiCallParams[]>(
    callss: Narrow<Callss>
  ): Promise<Ticks0Types.MulticallReturnType<Callss>>;
  async multicall<
    Callss extends Ticks0Types.MultiCallParams | Ticks0Types.MultiCallParams[]
  >(callss: Callss): Promise<unknown> {
    return await multicallMethods(Ticks0, this, callss, getContractByCodeHash);
  }
}
