/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  Address,
  Contract,
  ContractState,
  TestContractResult,
  HexString,
  ContractFactory,
  EventSubscribeOptions,
  EventSubscription,
  CallContractParams,
  CallContractResult,
  TestContractParams,
  ContractEvent,
  subscribeContractEvent,
  subscribeContractEvents,
  testMethod,
  callMethod,
  multicallMethods,
  fetchContractState,
  Asset,
  ContractInstance,
  getContractEventsCurrentCount,
  TestContractParamsWithoutMaps,
  TestContractResultWithoutMaps,
  SignExecuteContractMethodParams,
  SignExecuteScriptTxResult,
  signExecuteMethod,
  addStdIdToFields,
  encodeContractFields,
  Narrow,
} from "@alephium/web3";
import { default as Tick0ContractJson } from "../Tick0.ral.json";
import { getContractByCodeHash, registerContract } from "./contracts";
import * as types from "./types";

// Custom types for the contract
export namespace Tick0Types {
  export type Fields = {
    pool: HexString;
    data: types.TickData0;
    next: bigint;
  };

  export type State = ContractState<Fields>;

  export interface CallMethodTable {
    update: {
      params: CallContractParams<{ delta: bigint }>;
      result: CallContractResult<types.TickData0>;
    };
    insert: {
      params: CallContractParams<{ index: bigint; index2: bigint }>;
      result: CallContractResult<bigint>;
    };
  }
  export type CallMethodParams<T extends keyof CallMethodTable> =
    CallMethodTable[T]["params"];
  export type CallMethodResult<T extends keyof CallMethodTable> =
    CallMethodTable[T]["result"];
  export type MultiCallParams = Partial<{
    [Name in keyof CallMethodTable]: CallMethodTable[Name]["params"];
  }>;
  export type MultiCallResults<T extends MultiCallParams> = {
    [MaybeName in keyof T]: MaybeName extends keyof CallMethodTable
      ? CallMethodTable[MaybeName]["result"]
      : undefined;
  };
  export type MulticallReturnType<Callss extends MultiCallParams[]> = {
    [index in keyof Callss]: MultiCallResults<Callss[index]>;
  };

  export interface SignExecuteMethodTable {
    update: {
      params: SignExecuteContractMethodParams<{ delta: bigint }>;
      result: SignExecuteScriptTxResult;
    };
    insert: {
      params: SignExecuteContractMethodParams<{
        index: bigint;
        index2: bigint;
      }>;
      result: SignExecuteScriptTxResult;
    };
  }
  export type SignExecuteMethodParams<T extends keyof SignExecuteMethodTable> =
    SignExecuteMethodTable[T]["params"];
  export type SignExecuteMethodResult<T extends keyof SignExecuteMethodTable> =
    SignExecuteMethodTable[T]["result"];
}

class Factory extends ContractFactory<Tick0Instance, Tick0Types.Fields> {
  encodeFields(fields: Tick0Types.Fields) {
    return encodeContractFields(
      addStdIdToFields(this.contract, fields),
      this.contract.fieldsSig,
      types.AllStructs
    );
  }

  at(address: string): Tick0Instance {
    return new Tick0Instance(address);
  }

  tests = {
    update: async (
      params: TestContractParamsWithoutMaps<
        Tick0Types.Fields,
        { delta: bigint }
      >
    ): Promise<TestContractResultWithoutMaps<types.TickData0>> => {
      return testMethod(this, "update", params, getContractByCodeHash);
    },
    insert: async (
      params: TestContractParamsWithoutMaps<
        Tick0Types.Fields,
        { index: bigint; index2: bigint }
      >
    ): Promise<TestContractResultWithoutMaps<bigint>> => {
      return testMethod(this, "insert", params, getContractByCodeHash);
    },
  };

  stateForTest(initFields: Tick0Types.Fields, asset?: Asset, address?: string) {
    return this.stateForTest_(initFields, asset, address, undefined);
  }
}

// Use this object to test and deploy the contract
export const Tick0 = new Factory(
  Contract.fromJson(
    Tick0ContractJson,
    "",
    "85d196e2aa3d746c4cf09346ebdf60eb30f3bbb02aaed69f2c224a5417bc6d92",
    types.AllStructs
  )
);
registerContract(Tick0);

// Use this class to interact with the blockchain
export class Tick0Instance extends ContractInstance {
  constructor(address: Address) {
    super(address);
  }

  async fetchState(): Promise<Tick0Types.State> {
    return fetchContractState(Tick0, this);
  }

  view = {
    update: async (
      params: Tick0Types.CallMethodParams<"update">
    ): Promise<Tick0Types.CallMethodResult<"update">> => {
      return callMethod(Tick0, this, "update", params, getContractByCodeHash);
    },
    insert: async (
      params: Tick0Types.CallMethodParams<"insert">
    ): Promise<Tick0Types.CallMethodResult<"insert">> => {
      return callMethod(Tick0, this, "insert", params, getContractByCodeHash);
    },
  };

  transact = {
    update: async (
      params: Tick0Types.SignExecuteMethodParams<"update">
    ): Promise<Tick0Types.SignExecuteMethodResult<"update">> => {
      return signExecuteMethod(Tick0, this, "update", params);
    },
    insert: async (
      params: Tick0Types.SignExecuteMethodParams<"insert">
    ): Promise<Tick0Types.SignExecuteMethodResult<"insert">> => {
      return signExecuteMethod(Tick0, this, "insert", params);
    },
  };

  async multicall<Calls extends Tick0Types.MultiCallParams>(
    calls: Calls
  ): Promise<Tick0Types.MultiCallResults<Calls>>;
  async multicall<Callss extends Tick0Types.MultiCallParams[]>(
    callss: Narrow<Callss>
  ): Promise<Tick0Types.MulticallReturnType<Callss>>;
  async multicall<
    Callss extends Tick0Types.MultiCallParams | Tick0Types.MultiCallParams[]
  >(callss: Callss): Promise<unknown> {
    return await multicallMethods(Tick0, this, callss, getContractByCodeHash);
  }
}
