/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Address, HexString, Val, Struct } from "@alephium/web3";
import { default as allStructsJson } from "../structs.ral.json";
export const AllStructs = allStructsJson.map((json) => Struct.fromJson(json));
export interface AsyncTransfer extends Record<string, Val> {
  caller: Address;
  tokenId: HexString;
}
export interface Clawback extends Record<string, Val> {
  nonce: HexString;
  gas: bigint;
  id: HexString;
  amount: bigint;
}
export interface ClosePosition extends Record<string, Val> {
  token0: HexString;
  token1: HexString;
  caller: Address;
}
export interface CollectParams extends Record<string, Val> {
  token0: HexString;
  token1: HexString;
  configIndex: bigint;
  owner: Address;
  recipient: Address;
  tickLower: bigint;
  tickUpper: bigint;
  amount0Max: bigint;
  amount1Max: bigint;
}
export interface Config extends Record<string, Val> {
  tickSpacing: bigint;
  fee: bigint;
  feeProtocol: bigint;
}
export interface CreatePool extends Record<string, Val> {
  nonce: HexString;
  gas: bigint;
  deposit: bigint;
  token0: HexString;
  token1: HexString;
  token2: HexString;
  fee: bigint;
  lowerPrice: bigint;
  upperPrice: bigint;
  price: bigint;
  liquidity: bigint;
  spacing: bigint;
}
export interface DecreaseLiquidityParams extends Record<string, Val> {
  token0: HexString;
  token1: HexString;
  configIndex: bigint;
  owner: Address;
  tickLower: bigint;
  tickUpper: bigint;
  amount0Min: bigint;
  amount1Min: bigint;
}
export interface Deposit extends Record<string, Val> {
  salt: HexString;
  caller: Address;
}
export interface Donate extends Record<string, Val> {
  nonce: HexString;
  gas: bigint;
  token0: HexString;
  token1: HexString;
  tokenId: HexString;
  fee: bigint;
  amount: bigint;
  at: bigint;
}
export interface Exchange extends Record<string, Val> {
  nonce: HexString;
  nonce2: HexString;
  gas: bigint;
  id: HexString;
}
export interface ForceClose extends Record<string, Val> {
  caller: Address;
  maxGas: bigint;
  txCount: bigint;
}
export interface ModifyLiquidityParams extends Record<string, Val> {
  token0: HexString;
  token1: HexString;
  configIndex: bigint;
  owner: Address;
  tickLower: bigint;
  tickUpper: bigint;
  amount0Desired: bigint;
  amount1Desired: bigint;
  amount0Min: bigint;
  amount1Min: bigint;
}
export interface ModifyPosition extends Record<string, Val> {
  nonce: HexString;
  gas: bigint;
  deposit: bigint;
  token0: HexString;
  token1: HexString;
  fee: bigint;
  lower: bigint;
  upper: bigint;
  liquidity: bigint;
  amount0: bigint;
  amount1: bigint;
  ref1: bigint;
  ref2: bigint;
}
export interface ModifyPositionParams extends Record<string, Val> {
  owner: Address;
  tickLower: bigint;
  tickUpper: bigint;
  liquidityDelta: bigint;
}
export interface ProtocolFees extends Record<string, Val> {
  token0: bigint;
  token1: bigint;
}
export interface Rekey extends Record<string, Val> {
  nonce: HexString;
  gas: bigint;
  key: HexString;
}
export interface Reward extends Record<string, Val> {
  lastUpdateTimestamp: bigint;
  openTime: bigint;
  endTime: bigint;
  emmisionsPerSecond: bigint;
  rewardGrowthGlobal: bigint;
  rewardTotalEmissioned: bigint;
}
export interface Slot0 extends Record<string, Val> {
  sqrtPriceX96: bigint;
  tick: bigint;
  feeProtocol: bigint;
}
export interface StepComputations extends Record<string, Val> {
  sqrtPriceStartX96: bigint;
  tickNext: bigint;
  initialized: boolean;
  sqrtPriceNextX96: bigint;
  amountIn: bigint;
  amountOut: bigint;
  feeAmount: bigint;
}
export interface Swap extends Record<string, Val> {
  nonce: HexString;
  gas: bigint;
  token0: HexString;
  token1: HexString;
  fee: bigint;
  amount0: bigint;
  amount1: bigint;
}
export interface SwapCache extends Record<string, Val> {
  liquidityStart: bigint;
  feeProtocol: bigint;
}
export interface SwapParams extends Record<string, Val> {
  payer: Address;
  recipient: Address;
  token: HexString;
  payToken: HexString;
  toPay: bigint;
  withdrawToken: HexString;
  toWithdraw: bigint;
  data: HexString;
}
export interface SwapState extends Record<string, Val> {
  amountSpecifiedRemaining: bigint;
  amountCalculated: bigint;
  sqrtPriceX96: bigint;
  tick: bigint;
  feeGrowthGlobalX128: bigint;
  liquidity: bigint;
  protocolFee: bigint;
}
export interface TickData0 extends Record<string, Val> {
  liquidity: bigint;
  feeGrowth: [bigint, bigint, bigint];
}
export interface Transfer extends Record<string, Val> {
  nonce: HexString;
  gas: bigint;
  id: HexString;
  tokenId: HexString;
  amount: bigint;
}
