/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

export const DexAccountErrorCodes = {
  DexUserIsContract: BigInt("480"),
  InvalidOwner: BigInt("481"),
  ParentsNotSet: BigInt("483"),
};
