/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  RunScriptResult,
  DeployContractExecutionResult,
  NetworkId,
} from "@alephium/web3";
import {
  AlphUnstakeVault,
  AlphUnstakeVaultInstance,
  XAlphToken,
  XAlphTokenInstance,
  DistributorVault,
  DistributorVaultInstance,
  ALPHLock,
  ALPHLockInstance,
  RewardFeeCollector,
  RewardFeeCollectorInstance,
} from ".";
import { default as mainnetDeployments } from "../../deployments/.deployments.mainnet.json";
import { default as testnetDeployments } from "../../deployments/.deployments.testnet.json";
import { default as devnetDeployments } from "../../deployments/.deployments.devnet.json";

export type Deployments = {
  deployerAddress: string;
  contracts: {
    AlphUnstakeVault: DeployContractExecutionResult<AlphUnstakeVaultInstance>;
    XAlphToken: DeployContractExecutionResult<XAlphTokenInstance>;
    DistributorVault: DeployContractExecutionResult<DistributorVaultInstance>;
    ALPHLock: DeployContractExecutionResult<ALPHLockInstance>;
    RewardFeeCollector: DeployContractExecutionResult<RewardFeeCollectorInstance>;
  };
  scripts: { InitialStake: RunScriptResult };
};

function toDeployments(json: any): Deployments {
  const contracts = {
    AlphUnstakeVault: {
      ...json.contracts["AlphUnstakeVault"],
      contractInstance: AlphUnstakeVault.at(
        json.contracts["AlphUnstakeVault"].contractInstance.address
      ),
    },
    XAlphToken: {
      ...json.contracts["XAlphToken"],
      contractInstance: XAlphToken.at(
        json.contracts["XAlphToken"].contractInstance.address
      ),
    },
    DistributorVault: {
      ...json.contracts["DistributorVault"],
      contractInstance: DistributorVault.at(
        json.contracts["DistributorVault"].contractInstance.address
      ),
    },
    ALPHLock: {
      ...json.contracts["ALPHLock"],
      contractInstance: ALPHLock.at(
        json.contracts["ALPHLock"].contractInstance.address
      ),
    },
    RewardFeeCollector: {
      ...json.contracts["RewardFeeCollector"],
      contractInstance: RewardFeeCollector.at(
        json.contracts["RewardFeeCollector"].contractInstance.address
      ),
    },
  };
  return {
    ...json,
    contracts: contracts as Deployments["contracts"],
    scripts: { InitialStake: json.scripts["InitialStake"] },
  };
}

export function loadDeployments(
  networkId: NetworkId,
  deployerAddress?: string
): Deployments {
  const deployments =
    networkId === "mainnet"
      ? mainnetDeployments
      : networkId === "testnet"
      ? testnetDeployments
      : networkId === "devnet"
      ? devnetDeployments
      : undefined;
  if (deployments === undefined) {
    throw Error("The contract has not been deployed to the " + networkId);
  }
  const allDeployments: any[] = Array.isArray(deployments)
    ? deployments
    : [deployments];
  if (deployerAddress === undefined) {
    if (allDeployments.length > 1) {
      throw Error(
        "The contract has been deployed multiple times on " +
          networkId +
          ", please specify the deployer address"
      );
    } else {
      return toDeployments(allDeployments[0]);
    }
  }
  const result = allDeployments.find(
    (d) => d.deployerAddress === deployerAddress
  );
  if (result === undefined) {
    throw Error("The contract deployment result does not exist");
  }
  return toDeployments(result);
}
