/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  Address,
  Contract,
  ContractState,
  TestContractResult,
  HexString,
  ContractFactory,
  EventSubscribeOptions,
  EventSubscription,
  CallContractParams,
  CallContractResult,
  TestContractParams,
  ContractEvent,
  subscribeContractEvent,
  subscribeContractEvents,
  testMethod,
  callMethod,
  multicallMethods,
  fetchContractState,
  Asset,
  ContractInstance,
  getContractEventsCurrentCount,
  TestContractParamsWithoutMaps,
  TestContractResultWithoutMaps,
  SignExecuteContractMethodParams,
  SignExecuteScriptTxResult,
  signExecuteMethod,
  addStdIdToFields,
  encodeContractFields,
  Narrow,
} from "@alephium/web3";
import { default as DummyFeeCollectorContractJson } from "../examples/DummyFeeCollector.ral.json";
import { getContractByCodeHash, registerContract } from "./contracts";
import * as types from "./types";

// Custom types for the contract
export namespace DummyFeeCollectorTypes {
  export type State = Omit<ContractState<any>, "fields">;

  export interface CallMethodTable {
    collectProtocolFees: {
      params: CallContractParams<{ recipient: Address; data: HexString }>;
      result: CallContractResult<bigint>;
    };
  }
  export type CallMethodParams<T extends keyof CallMethodTable> =
    CallMethodTable[T]["params"];
  export type CallMethodResult<T extends keyof CallMethodTable> =
    CallMethodTable[T]["result"];
  export type MultiCallParams = Partial<{
    [Name in keyof CallMethodTable]: CallMethodTable[Name]["params"];
  }>;
  export type MultiCallResults<T extends MultiCallParams> = {
    [MaybeName in keyof T]: MaybeName extends keyof CallMethodTable
      ? CallMethodTable[MaybeName]["result"]
      : undefined;
  };
  export type MulticallReturnType<Callss extends MultiCallParams[]> = {
    [index in keyof Callss]: MultiCallResults<Callss[index]>;
  };

  export interface SignExecuteMethodTable {
    collectProtocolFees: {
      params: SignExecuteContractMethodParams<{
        recipient: Address;
        data: HexString;
      }>;
      result: SignExecuteScriptTxResult;
    };
  }
  export type SignExecuteMethodParams<T extends keyof SignExecuteMethodTable> =
    SignExecuteMethodTable[T]["params"];
  export type SignExecuteMethodResult<T extends keyof SignExecuteMethodTable> =
    SignExecuteMethodTable[T]["result"];
}

class Factory extends ContractFactory<DummyFeeCollectorInstance, {}> {
  encodeFields() {
    return encodeContractFields({}, this.contract.fieldsSig, types.AllStructs);
  }

  at(address: string): DummyFeeCollectorInstance {
    return new DummyFeeCollectorInstance(address);
  }

  tests = {
    collectProtocolFees: async (
      params: Omit<
        TestContractParamsWithoutMaps<
          never,
          { recipient: Address; data: HexString }
        >,
        "initialFields"
      >
    ): Promise<TestContractResultWithoutMaps<bigint>> => {
      return testMethod(
        this,
        "collectProtocolFees",
        params,
        getContractByCodeHash
      );
    },
  };

  stateForTest(initFields: {}, asset?: Asset, address?: string) {
    return this.stateForTest_(initFields, asset, address, undefined);
  }
}

// Use this object to test and deploy the contract
export const DummyFeeCollector = new Factory(
  Contract.fromJson(
    DummyFeeCollectorContractJson,
    "",
    "ad6247fed8cfa76bbfb85159fdd592a95f22507147f16662378d0d2926b719c7",
    types.AllStructs
  )
);
registerContract(DummyFeeCollector);

// Use this class to interact with the blockchain
export class DummyFeeCollectorInstance extends ContractInstance {
  constructor(address: Address) {
    super(address);
  }

  async fetchState(): Promise<DummyFeeCollectorTypes.State> {
    return fetchContractState(DummyFeeCollector, this);
  }

  view = {
    collectProtocolFees: async (
      params: DummyFeeCollectorTypes.CallMethodParams<"collectProtocolFees">
    ): Promise<
      DummyFeeCollectorTypes.CallMethodResult<"collectProtocolFees">
    > => {
      return callMethod(
        DummyFeeCollector,
        this,
        "collectProtocolFees",
        params,
        getContractByCodeHash
      );
    },
  };

  transact = {
    collectProtocolFees: async (
      params: DummyFeeCollectorTypes.SignExecuteMethodParams<"collectProtocolFees">
    ): Promise<
      DummyFeeCollectorTypes.SignExecuteMethodResult<"collectProtocolFees">
    > => {
      return signExecuteMethod(
        DummyFeeCollector,
        this,
        "collectProtocolFees",
        params
      );
    },
  };

  async multicall<Calls extends DummyFeeCollectorTypes.MultiCallParams>(
    calls: Calls
  ): Promise<DummyFeeCollectorTypes.MultiCallResults<Calls>>;
  async multicall<Callss extends DummyFeeCollectorTypes.MultiCallParams[]>(
    callss: Narrow<Callss>
  ): Promise<DummyFeeCollectorTypes.MulticallReturnType<Callss>>;
  async multicall<
    Callss extends
      | DummyFeeCollectorTypes.MultiCallParams
      | DummyFeeCollectorTypes.MultiCallParams[]
  >(callss: Callss): Promise<unknown> {
    return await multicallMethods(
      DummyFeeCollector,
      this,
      callss,
      getContractByCodeHash
    );
  }
}
