/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  Address,
  Contract,
  ContractState,
  TestContractResult,
  HexString,
  ContractFactory,
  EventSubscribeOptions,
  EventSubscription,
  CallContractParams,
  CallContractResult,
  TestContractParams,
  ContractEvent,
  subscribeContractEvent,
  subscribeContractEvents,
  testMethod,
  callMethod,
  multicallMethods,
  fetchContractState,
  Asset,
  ContractInstance,
  getContractEventsCurrentCount,
  TestContractParamsWithoutMaps,
  TestContractResultWithoutMaps,
  SignExecuteContractMethodParams,
  SignExecuteScriptTxResult,
  signExecuteMethod,
  addStdIdToFields,
  encodeContractFields,
  Narrow,
} from "@alephium/web3";
import { default as RevertingStakingDappContractJson } from "../test/RevertingStakingDapp.ral.json";
import { getContractByCodeHash, registerContract } from "./contracts";
import * as types from "./types";

// Custom types for the contract
export namespace RevertingStakingDappTypes {
  export type Fields = {
    stakeVault: HexString;
    stakedAmount: bigint;
  };

  export type State = ContractState<Fields>;

  export interface CallMethodTable {
    onStake: {
      params: CallContractParams<{ user: Address; amount: bigint }>;
      result: CallContractResult<null>;
    };
    onUnstake: {
      params: CallContractParams<{ user: Address; amount: bigint }>;
      result: CallContractResult<null>;
    };
  }
  export type CallMethodParams<T extends keyof CallMethodTable> =
    CallMethodTable[T]["params"];
  export type CallMethodResult<T extends keyof CallMethodTable> =
    CallMethodTable[T]["result"];
  export type MultiCallParams = Partial<{
    [Name in keyof CallMethodTable]: CallMethodTable[Name]["params"];
  }>;
  export type MultiCallResults<T extends MultiCallParams> = {
    [MaybeName in keyof T]: MaybeName extends keyof CallMethodTable
      ? CallMethodTable[MaybeName]["result"]
      : undefined;
  };
  export type MulticallReturnType<Callss extends MultiCallParams[]> = {
    [index in keyof Callss]: MultiCallResults<Callss[index]>;
  };

  export interface SignExecuteMethodTable {
    onStake: {
      params: SignExecuteContractMethodParams<{
        user: Address;
        amount: bigint;
      }>;
      result: SignExecuteScriptTxResult;
    };
    onUnstake: {
      params: SignExecuteContractMethodParams<{
        user: Address;
        amount: bigint;
      }>;
      result: SignExecuteScriptTxResult;
    };
  }
  export type SignExecuteMethodParams<T extends keyof SignExecuteMethodTable> =
    SignExecuteMethodTable[T]["params"];
  export type SignExecuteMethodResult<T extends keyof SignExecuteMethodTable> =
    SignExecuteMethodTable[T]["result"];
}

class Factory extends ContractFactory<
  RevertingStakingDappInstance,
  RevertingStakingDappTypes.Fields
> {
  encodeFields(fields: RevertingStakingDappTypes.Fields) {
    return encodeContractFields(
      addStdIdToFields(this.contract, fields),
      this.contract.fieldsSig,
      types.AllStructs
    );
  }

  consts = {
    ErrorCodes: {
      StakeVaultCallerOnly: BigInt("60"),
      InvalidUnstakedAmount: BigInt("61"),
      RevertedOnUnstake: BigInt("62"),
    },
  };

  at(address: string): RevertingStakingDappInstance {
    return new RevertingStakingDappInstance(address);
  }

  tests = {
    onStake: async (
      params: TestContractParamsWithoutMaps<
        RevertingStakingDappTypes.Fields,
        { user: Address; amount: bigint }
      >
    ): Promise<TestContractResultWithoutMaps<null>> => {
      return testMethod(this, "onStake", params, getContractByCodeHash);
    },
    onUnstake: async (
      params: TestContractParamsWithoutMaps<
        RevertingStakingDappTypes.Fields,
        { user: Address; amount: bigint }
      >
    ): Promise<TestContractResultWithoutMaps<null>> => {
      return testMethod(this, "onUnstake", params, getContractByCodeHash);
    },
  };

  stateForTest(
    initFields: RevertingStakingDappTypes.Fields,
    asset?: Asset,
    address?: string
  ) {
    return this.stateForTest_(initFields, asset, address, undefined);
  }
}

// Use this object to test and deploy the contract
export const RevertingStakingDapp = new Factory(
  Contract.fromJson(
    RevertingStakingDappContractJson,
    "",
    "0a3718843c99af33999d7b6a8086bf941b6dee23b82a29808d9c9757feb2ddb0",
    types.AllStructs
  )
);
registerContract(RevertingStakingDapp);

// Use this class to interact with the blockchain
export class RevertingStakingDappInstance extends ContractInstance {
  constructor(address: Address) {
    super(address);
  }

  async fetchState(): Promise<RevertingStakingDappTypes.State> {
    return fetchContractState(RevertingStakingDapp, this);
  }

  view = {
    onStake: async (
      params: RevertingStakingDappTypes.CallMethodParams<"onStake">
    ): Promise<RevertingStakingDappTypes.CallMethodResult<"onStake">> => {
      return callMethod(
        RevertingStakingDapp,
        this,
        "onStake",
        params,
        getContractByCodeHash
      );
    },
    onUnstake: async (
      params: RevertingStakingDappTypes.CallMethodParams<"onUnstake">
    ): Promise<RevertingStakingDappTypes.CallMethodResult<"onUnstake">> => {
      return callMethod(
        RevertingStakingDapp,
        this,
        "onUnstake",
        params,
        getContractByCodeHash
      );
    },
  };

  transact = {
    onStake: async (
      params: RevertingStakingDappTypes.SignExecuteMethodParams<"onStake">
    ): Promise<
      RevertingStakingDappTypes.SignExecuteMethodResult<"onStake">
    > => {
      return signExecuteMethod(RevertingStakingDapp, this, "onStake", params);
    },
    onUnstake: async (
      params: RevertingStakingDappTypes.SignExecuteMethodParams<"onUnstake">
    ): Promise<
      RevertingStakingDappTypes.SignExecuteMethodResult<"onUnstake">
    > => {
      return signExecuteMethod(RevertingStakingDapp, this, "onUnstake", params);
    },
  };
}
