/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  Address,
  ExecutableScript,
  ExecuteScriptParams,
  ExecuteScriptResult,
  Script,
  SignerProvider,
  HexString,
} from "@alephium/web3";
import { getContractByCodeHash } from "./contracts";
import { default as CollectProtocolCLMMTokenScriptJson } from "../CollectProtocolCLMMToken.ral.json";
import { default as CollectProtocolCPMMTokenScriptJson } from "../CollectProtocolCPMMToken.ral.json";
import { default as ConnectToDappScriptJson } from "../ConnectToDapp.ral.json";
import { default as InitialStakeScriptJson } from "../InitialStake.ral.json";
import { default as XAlphUnlockAndStartUnstakeScriptJson } from "../XAlphUnlockAndStartUnstake.ral.json";
import * as types from "./types";

export const CollectProtocolCLMMToken = new ExecutableScript<{
  collector: HexString;
  factory: HexString;
  token0: HexString;
  token1: HexString;
  configIndex: bigint;
  tokenId: HexString;
}>(
  Script.fromJson(CollectProtocolCLMMTokenScriptJson, "", types.AllStructs),
  getContractByCodeHash
);

export const CollectProtocolCPMMToken = new ExecutableScript<{
  collector: HexString;
  factory: HexString;
  token0: HexString;
  token1: HexString;
}>(
  Script.fromJson(CollectProtocolCPMMTokenScriptJson, "", types.AllStructs),
  getContractByCodeHash
);

export const ConnectToDapp = new ExecutableScript<{
  vault: HexString;
  contractId: HexString;
  xAlph: HexString;
}>(
  Script.fromJson(ConnectToDappScriptJson, "", types.AllStructs),
  getContractByCodeHash
);

export const InitialStake = new ExecutableScript<{
  xalph: HexString;
  amount: bigint;
}>(
  Script.fromJson(InitialStakeScriptJson, "", types.AllStructs),
  getContractByCodeHash
);

export const XAlphUnlockAndStartUnstake = new ExecutableScript<{
  xAlphToken: HexString;
  xAlphStakeVault: HexString;
  amount: bigint;
}>(
  Script.fromJson(XAlphUnlockAndStartUnstakeScriptJson, "", types.AllStructs),
  getContractByCodeHash
);
